/*******************************************************************************
DO-FILE: bnr_report_annual_standard.do
VERSION: 2.5.0 (4 September 2026)
PURPOSE: Reusable putpdf composition for the standard annual CVD surveillance
         section.

CALLER:
  bnr_report_annual_s1_build.do only.

SOURCE BOUNDARY:
  This file reads only the two declared approved public release CSVs selected
  and checksum-validated by Step 1. It never reads confidential source data and
  it does not recalculate published surveillance rates.

DESIGN CONTRACT:
  - A4 portrait annual-report publication, not a printed dashboard.
  - Montserrat Medium is used for titling and Montserrat for body copy.
  - The UWI crest, restrained BNR palette and briefing-style white space provide
    the visual identity.
  - The cover and Year in Brief use fixed invisible-table layout grids so the
    page is composed deliberately rather than allowed to flow unpredictably.
  - Results graphics show the complete approved annual time series.
  - Exact result tables show the latest five complete years in wide form.
  - Public-facing headings use counts/events/deaths rather than "burden".
  - Graph furniture is deliberately sparse.
  - DCO/linkage uncertainty is shown as a pale band; published statistical
    confidence intervals are shown as whiskers.
  - Published five-year count comparators are used where they exist.
  - Interpretation remains analyst-owned in the year-specific interpretation
    file; this composition file does not generate editorial conclusions.
  - Special chapter composition remains outside this file.

DESIGN PASS 2.2.0:
  - Keep summary-card backgrounds continuous behind labels and values.
  - Simplify interpretation callouts to one continuous pale panel.
  - Widen annual graphics, move legends to 12 o'clock, remove axis lines and
    add same-colour observed-value markers to line charts.
  - Increase use of published uncertainty without combining distinct sources:
    DCO linkage ranges are shaded; statistical 95% confidence intervals use
    whiskers.
  - Add a concise quarterly hospital-recorded "How the year unfolded" view.
  - Rebuild completeness graphics as labelled five-year tile matrices.
  - Expand Methods into a publication-grade technical section covering
    ascertainment, definitions, equations, uncertainty, disclosure and release
    governance.
  - Keep analytical definitions, release selection and workflow boundaries
    unchanged.

DESIGN PASS 2.4.0:
  - Rebuild the year-in-brief page as headline cards, one monthly event chart
    and three findings; remove the uninformative mini-trends and the separate
    quarterly page.
  - Round the four headline values and published confidence intervals to whole
    numbers for this high-level page.
  - Use explicit card spacer cells and white card surfaces with coloured top
    rules, avoiding putpdf's opaque text-background artefact.
  - Keep the disease-specific CVD, Heart and Stroke chapter expansion for the
    next design stage.

DESIGN PASS 2.5.0:
  - Replace combined subtype pages with a consistent All-CVD, Heart and Stroke
    sequence for counts, rates, women and men, and broad age patterns.
  - Apply the same disease-specific sequence to mortality, preserving Primary
    and Inclusive mortality definitions.
  - Keep all metric selection in an included, readable Stata section so the
    established annual workflow and publication boundary are unchanged.

DESIGN PASS 2.3.0:
  - Establish a single report type scale and a white-card, coloured-rule visual
    treatment that avoids opaque text-background artefacts in putpdf output.
  - Standardise metric strips, interpretation callouts and data-table headers
    around rules and whitespace rather than broad cell shading.
  - Page furniture is applied later by the Step 1 controlled PDF helper; it is
    deliberately outside this composition file and has no analytical role.
*******************************************************************************/

*******************************************************************************
* BNR ANALYST GUIDE - REUSABLE STANDARD SECTION
*
* BNR ANALYST: DO NOT EDIT THIS FILE for routine annual production.
* This is the invariant composition layer shared across reporting years. It
* selects already-published rows, draws the standard graphics and tables, and
* inserts analyst-owned narrative locals at predetermined positions. It must
* never read confidential data or become a second metric-calculation workflow.
*
* Safe annual narrative editing belongs in the year-specific interpretation
* DO file. A structural or graphical change here is a maintained template
* change: review it, build a new candidate version and inspect the whole PDF.
*
* IMPORTANT: the large `if 0 { ... }` block is disabled legacy reference code.
* Do not reactivate, edit, extract or reorder it during routine work.
*******************************************************************************

version 19.0

* -----------------------------------------------------------------------------
* 1. Required context and visual language
* -----------------------------------------------------------------------------
* INVARIANT TEMPLATE SETUP - DO NOT EDIT ROUTINELY.
* Confirm the caller supplied a report year and two release IDs, require the
* crest, define the single palette/type scale, and create the private figures
* directory. These locals are reused by the standard and Special chapters.

if "`report_year4'" == "" {
    display as error "Annual standard composition requires local report_year4."
    exit 198
}
if "`event_release'" == "" | "`mortality_release'" == "" {
    display as error "Annual standard composition requires declared public release IDs."
    exit 198
}

local uwi_crest "$BNR_REPO/site/assets/images/uwi-crestonly-20p.png"
capture confirm file "`uwi_crest'"
if _rc {
    display as error "Required UWI crest not found: `uwi_crest'"
    exit 601
}

* RGB strings are retained as locals so the 2025 Special chapter can reuse them.
local bnr_ink       "44 62 80"
local bnr_teal      "4 81 116"
local bnr_primary   "43 115 136"
local bnr_secondary "91 139 151"
local bnr_women     "122 85 134"
local bnr_men       "45 103 141"
local bnr_stroke    "47 126 96"
local bnr_heart     "178 95 82"
local bnr_under70   "216 156 96"
local bnr_70plus    "122 135 148"
local bnr_pale      "240 246 248"
local bnr_pale2     "248 249 250"
local bnr_white     "255 255 255"
local bnr_rule      "222 226 230"
local bnr_muted     "102 102 102"
local bnr_green     "214 237 223"
local bnr_amber     "255 231 168"
local bnr_red       "243 198 204"

* Base CVD colour: 4 81 116
local bnr_women_all_cvd "4 116 161"     // lighter
local bnr_men_all_cvd   "4 46 71"       // darker

* Base Heart colour: 178 95 82
local bnr_women_heart "233 130 112" // lighter
local bnr_men_heart   "123 60 52"   // darker

* Base Stroke colour: 47 126 96
local bnr_women_stroke "72 171 131" // lighter
local bnr_men_stroke   "22 81 61"   // darker


* * Base CVD colour: 4 81 116
* local bnr_women_all_cvd "4 101 141"    // lighter
* local bnr_men_all_cvd   "4 61 91"      // darker
* * Base Heart colour: 178 95 82
* local bnr_women_heart "211 118 102"  // lighter
* local bnr_men_heart   "145 72 62"    // darker
* * Base Stroke colour: 47 126 96
* local bnr_women_stroke "64 153 119"  // lighter
* local bnr_men_stroke   "30 99 73"    // darker

* Publication typography. These fonts are part of the intended analytics
* environment. A separate report style sheet will be produced once the visual
* system has stabilised.
local font_title      "Montserrat Medium"
local font_body       "Montserrat"
local font_body_med   "Montserrat Medium"
local font_body_light "Montserrat Light"

* One reusable A4 type scale. Page-specific design may use these local names,
* but must not introduce a second heading hierarchy.
local size_chapter  18
local size_page     14
local size_section  11
local size_deck      8
local size_body      8.4
local size_table     7.8
local size_label     7.5
local size_value    14

local first_table_year = `report_year_num' - 4

capture mkdir "`candidate_dir'/figures"
local annual_figure_dir "`candidate_dir'/figures"

* -----------------------------------------------------------------------------
* 2. Read the two approved public releases once
* -----------------------------------------------------------------------------
* INVARIANT PUBLIC-DATA BOUNDARY - DO NOT EDIT.
* Import the two Step 1 checksum-validated public CSVs, convert only published
* numeric columns and cache them as temporary Stata datasets. No confidential
* source, linkage record or private analytical input may be introduced here.

tempfile annual_event_data annual_mortality_data

import delimited using "`event_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_month period_quarter period_complete value numerator denominator ///
        linkage_lower_value linkage_upper_value ci_lower_value ci_upper_value ///
        comparison_n {
    capture destring `v', replace force
}
save "`annual_event_data'", replace

import delimited using "`mortality_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_complete value numerator denominator ///
        ci_lower_value ci_upper_value comparison_n {
    capture destring `v', replace force
}
save "`annual_mortality_data'", replace

* -----------------------------------------------------------------------------
* 3. Latest-year values used on cover-summary cards
* -----------------------------------------------------------------------------
* INVARIANT METRIC SELECTION - DO NOT EDIT ROUTINELY.
* Select the four headline results and their released confidence limits. This
* block formats existing public values; it does not calculate surveillance
* rates. Changes to metric IDs, scopes, definitions or strata require formal
* template review because they alter the meaning of the summary page.

local yib_event_count "Not available"
local yib_event_rate "Not available"
local yib_event_rate_ci ""
local yib_death_count "Not available"
local yib_death_rate "Not available"
local yib_death_rate_ci ""

use "`annual_event_data'", clear
preserve
    keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_event_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "CVD-INCIDENCE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_event_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_event_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore
use "`annual_mortality_data'", clear
preserve
    keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        case_definition == "primary_clear_likely" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_death_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "MORT-RATE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        case_definition == "primary_clear_likely" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_death_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_death_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore
* -----------------------------------------------------------------------------
* 4. Plain cover
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION BLOCK - NOT A ROUTINE ANALYST EDIT.
* Compose the cover within one fixed invisible table so pagination is stable.
* Text or branding changes should be treated as report-template changes and
* checked against the finished, furniture-stamped PDF.

* The cover is held in one invisible layout grid. This avoids the page-flow
* behaviour of the first prototype, where each cover element could land on a
* separate page.

putpdf table cover = (5,1), width(15%) border(all, nil) halign(center)
putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = (" ")
putpdf table cover(4,1) = (" ")
putpdf table cover(5,1) = image("`uwi_crest'"), halign(center)

putpdf table cover = (8,12), width(88%) border(all, nil) halign(center)
putpdf table cover(1,1), colspan(12)
putpdf table cover(2,1), colspan(12)
putpdf table cover(3,1), colspan(12)
putpdf table cover(4,1), colspan(12)
putpdf table cover(5,1), colspan(12)
putpdf table cover(6,1), colspan(12)
putpdf table cover(7,1), colspan(12)
putpdf table cover(8,1), colspan(12)

putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = ("BARBADOS NATIONAL REGISTRY"), ///
    halign(center) font("`font_title'", 10, "`bnr_teal'")
putpdf table cover(4,1) = ("Annual cardiovascular disease report"), ///
    halign(center) bold font("`font_title'", 24, "`bnr_ink'")
putpdf table cover(5,1) = ("`report_year4'"), ///
    halign(center) bold font("`font_title'", 30, "`bnr_ink'")
putpdf table cover(6,1) = ("Cardiovascular disease events and mortality in Barbados"), ///
    halign(center) font("`font_body'", 11, "`bnr_muted'")
putpdf table cover(7,1) = (" ")
putpdf table cover(8,1) = ("The University of the West Indies | Cave Hill Campus"), ///
    halign(center) font("`font_body'", 8, "`bnr_muted'")



* -----------------------------------------------------------------------------
* 5A. Report information and front matter
* -----------------------------------------------------------------------------
* MAINTAINED FRONT-MATTER BLOCK.
* This page is public report metadata and explanatory context. Update authors,
* affiliations, acknowledgements and contact details when the report ownership
* changes. Do not alter the release identifiers or analytical definitions here.
*
* The report year, event release and mortality release are supplied by the
* controlled annual build workflow.

putpdf pagebreak

putpdf paragraph, font("`font_body'", 1)
putpdf text ("About this report"), ///
    bold font("`font_title'", 19, "`bnr_ink'") linebreak

putpdf text ("Annual cardiovascular disease report `report_year4'"), ///
    bold font("`font_title'", 11, "`bnr_teal'") linebreak

putpdf text ("Cardiovascular disease events and mortality in Barbados"), ///
    font("`font_body'", 9, "`bnr_muted'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Purpose and scope"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("This report provides an annual overview of cardiovascular disease events and mortality in Barbados. It presents published All-CVD, Heart and Stroke results, together with selected sex and age summaries where those measures are available in the approved public release. The report is intended to support decision-making by government, hospitals, clinics, public-health teams, researchers and other partners."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 2)

putpdf text ///
    ("The report uses complete annual observations from the approved public event and mortality releases. It does not read confidential source records or recalculate the published surveillance measures. Estimates should be interpreted alongside the definitions, coverage notes and uncertainty information provided in the report."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Report information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf table report_frontmatter = (6,2), width(100%) border(all, nil)

putpdf table report_frontmatter(1,1) = ("Report")
putpdf table report_frontmatter(1,2) = ///
    ("Annual cardiovascular disease report `report_year4'")

putpdf table report_frontmatter(2,1) = ("Prepared by")
putpdf table report_frontmatter(2,2) = ///
    ("Christina Howitt; Ian Hambleton; Jacqueline Campbell")

putpdf table report_frontmatter(3,1) = ("Institution")
putpdf table report_frontmatter(3,2) = ///
    ("Barbados National Registry | The University of the West Indies, Cave Hill Campus")

putpdf table report_frontmatter(4,1) = ("Approved data releases")
putpdf table report_frontmatter(4,2) = ///
    ("CVD events: `event_release' | CVD mortality: `mortality_release'")

putpdf table report_frontmatter(5,1) = ("Online report")
putpdf table report_frontmatter(5,2) = ///
    ("https://uwi-bnr.github.io/info-hub/")

putpdf table report_frontmatter(6,1) = ("Suggested citation")
putpdf table report_frontmatter(6,2) = ///
    ("Barbados National Registry. Annual cardiovascular disease report `report_year4': cardiovascular disease events and mortality in Barbados. The University of the West Indies, Cave Hill Campus.")

putpdf table report_frontmatter(.,.), ///
    font("`font_body'", 7.8, "`bnr_ink'") ///
    bgcolor("`bnr_white'")

putpdf table report_frontmatter(1,.), ///
    bold font("`font_title'", 7.8, "`bnr_teal'") ///
    border(top, single, "`bnr_teal'") ///
    border(bottom, single, "`bnr_rule'")

putpdf table report_frontmatter(2/6,1), ///
    bold font("`font_title'", 7.8, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Acknowledgements"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("The Barbados National Registry acknowledges the clinical, hospital, registry, data-management and public-health teams whose work supports the production of this surveillance report. The report should be read as a surveillance product and not as a substitute for clinical judgement, formal cause-of-death coding or other official statistical series."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Further information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("Definitions, ascertainment rules, mortality classifications, uncertainty measures, data availability and disclosure controls are described in the Methods chapter. The latest public report and associated data products are available at: https://uwi-bnr.github.io/info-hub/"), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ///
    ("Publication note: This edition is produced through the controlled BNR annual-report build, approval and publication workflow. The public version is the approved version deposited through that workflow."), ///
    font("`font_body'", 7.8, "`bnr_muted'")

* Begin the existing Year in Brief page.
putpdf pagebreak


* -----------------------------------------------------------------------------
* 5B. Year in brief - one-page visual summary
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION AND METRIC-SELECTION BLOCK.
* BNR ANALYST: do not change filters or calculations here. This block draws the
* approved monthly hospital-recorded series, lays out four headline cards and
* inserts three editable messages defined in the year interpretation file.

* Month-on-month CVD events.
* All years other than the report year are faded lines without dots.
* The current report year is overlaid as the prominent connected line.
* This automatically updates for future annual reports.

local yib_monthly_fig "`annual_figure_dir'/yib_monthly_events.png"
use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & ///
    period_type == "monthly" & ///
    event_type == "all_cvd" & ///
    sex == "all" & ///
    age_group == "all" & ///
    ascertainment_scope == "hospital_only" & ///
    statistic == "monthly_count" & ///
    period_complete == 1
quietly count

if r(N) >= 2 {
    sort period_year period_month

    * Create one variable for each historical year.
    * The current report year is excluded from these variables.
    separate value if period_year != `report_year_num', ///
        by(period_year) generate(yib_historical)

    * Create rolling comparator years 
    unab yib_historical_vars : yib_historical*
    local yib_historical_colours
    foreach v of local yib_historical_vars {
        local yib_historical_colours `"`yib_historical_colours' "`bnr_teal'%20""'
    }

    #delimit ; 
    twoway 
        (line yib_historical* period_month, sort lcolor(`yib_historical_colours') lwidth(thin)) 
        (connected value period_month if period_year == `report_year_num', sort 
            lcolor("`bnr_teal'") mcolor("`bnr_teal'") msymbol(O) msize(5) 
            lwidth(1))
            , 
		plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
		graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))
        xlabel(1 "Jan" 2 " " 3 " " 4 "Apr" 5 " " 6 " " 
               7 "Jul" 8 " " 9 " " 10 "Oct" 11 " " 12 " ",
               labsize(9) noticks nogrid)
        ylabel(#4, angle(horizontal) labsize(9) noticks nogrid) 
        xscale(noline range(0.5(1)12.5)) yscale(noline range(70(5)110)) 
        xtitle("") ytitle("", size(vsmall)) legend(off) 
        xsize(7.6) ysize(1.55)
        name(yib);
    #delimit cr 
    graph export "`yib_monthly_fig'", replace width(2600)
}

putpdf pagebreak
putpdf paragraph, font("`font_body'", 1)
putpdf text ("`report_year4' in brief"), bold font("`font_title'", 20, "`bnr_ink'") linebreak
putpdf text ("The latest complete year at a glance"), ///
    font("`font_body'", 9, "`bnr_muted'")

* Four explicit cards. Column 2 and row 4 are intentional spacer cells. White
* card surfaces eliminate putpdf's visible opaque text-background artefact.
putpdf table yib_cards = (7,3), width(100%) border(all, nil)
forvalues r = 1/7 {
    putpdf table yib_cards(`r',2) = ("")
}
putpdf table yib_cards(4,1) = (""), font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(4,3) = (""), font("`font_title'", 2.5, "`bnr_teal'")

putpdf table yib_cards(1,1) = ("CVD EVENTS"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,1) = ("`yib_event_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,1) = ("Primary national estimate"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(1,3) = ("CVD EVENT RATE"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,3) = ("`yib_event_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,3) = ("Age-standardised | `yib_event_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,1) = ("CVD DEATHS"), bold font("`font_title'", 7.5, "`bnr_heart'")
putpdf table yib_cards(6,1) = ("`yib_death_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,1) = ("Primary definition"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,3) = ("CVD MORTALITY RATE"), bold font("`font_title'", 7.5, "`bnr_secondary'")
putpdf table yib_cards(6,3) = ("`yib_death_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,3) = ("Age-standardised | `yib_death_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(.,.), bgcolor("`bnr_white'")
putpdf table yib_cards(1,1), border(top, single, "`bnr_teal'")
putpdf table yib_cards(1,3), border(top, single, "`bnr_teal'")
putpdf table yib_cards(5,1), border(top, single, "`bnr_heart'")
putpdf table yib_cards(5,3), border(top, single, "`bnr_secondary'")

putpdf paragraph, font("`font_body'", 1)
putpdf text ("How the year unfolded"), bold font("`font_title'", 10.5, "`bnr_ink'")
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Monthly hospital-recorded All-CVD events in `report_year4'. National estimates are annual because death-record ascertainment is applied after the year closes."), font("`font_body'", 7.4, "`bnr_muted'")
capture confirm file "`yib_monthly_fig'"
if !_rc {
    putpdf table yib_monthly = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table yib_monthly(1,1) = image("`yib_monthly_fig'")
}

putpdf paragraph, font("`font_body'", 1)
putpdf text ("What stood out in `report_year4'?"), ///
    bold font("`font_title'", 10.5, "`bnr_ink'")

putpdf table yib_messages = (3,12), width(100%) border(all, nil)
forvalues rr = 1/3 {
    putpdf table yib_messages(`rr',1)
    putpdf table yib_messages(`rr',2), colspan(11)
    putpdf table yib_messages(`rr',1) = ("0`rr'"), ///
        halign(center) bold font("`font_title'", 9, "`bnr_teal'")
}
putpdf table yib_messages(1,2) = ("`annual_summary_message_1'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(2,2) = ("`annual_summary_message_2'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(3,2) = ("`annual_summary_message_3'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")


* -----------------------------------------------------------------------------
* 6. Stage 3 disease-specific event and mortality sections
* -----------------------------------------------------------------------------

* INVARIANT INCLUDE POINT - DO NOT MOVE.
* The included template creates all live Chapter 1 and Chapter 2 pages in this
* position. Its internal comments identify each graphic, table and narrative
* hook. Moving the include changes report order and page flow.

** include "$BNR_REPO/scripts/stata/reporting/templates/bnr_report_annual_stage3_sections.do"



* -----------------------------------------------------------------------------
* 16. How complete is the picture? - E1/E2 quality matrices
* -----------------------------------------------------------------------------

* CHAPTER 3 - MAINTAINED QUALITY PRESENTATION.
* BNR ANALYST: the graphics may be refined only as an approved template change.
* Do not change the public metrics or definitions. The first matrix describes
* the published DCO contribution to Primary national event estimates; the
* second describes reliance on Possible deaths within Inclusive mortality.
* Percentages are presentation summaries of released aggregate counts.

local fig_e1 "`annual_figure_dir'/quality_event_dco.png"
local fig_e2 "`annual_figure_dir'/quality_possible_deaths.png"
local quality_first_year = `report_year_num' - 14

use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    ((ascertainment_scope == "additional_dco" & mortality_definition == "primary") | ///
     (ascertainment_scope == "hospital_plus_dco" & mortality_definition == "primary"))
keep period_year event_type ascertainment_scope value
reshape wide value, i(period_year event_type) j(ascertainment_scope) string
gen double quality_pct = 100 * valueadditional_dco / valuehospital_plus_dco
gen byte quality_band = cond(quality_pct < 10, 1, cond(quality_pct < 15, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)

local x_range_min = `quality_first_year' - 1 
local x_range_max = `report_year_num' + 1

if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_mort)
      ;
    #delimit cr
    graph export "`fig_e1'", replace width(2800)
}

use "`annual_mortality_data'", clear
keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    inlist(case_definition, "primary_clear_likely", "upper_clear_likely_possible")
keep period_year event_type case_definition value
reshape wide value, i(period_year event_type) j(case_definition) string
gen double quality_pct = 100 * ///
    (valueupper_clear_likely_possible - valueprimary_clear_likely) / ///
    valueupper_clear_likely_possible
gen byte quality_band = cond(quality_pct < 20, 1, cond(quality_pct < 30, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)
if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_dco)
      ;
    #delimit cr
    graph export "`fig_e2'", replace width(2800)
}

putpdf pagebreak
putpdf paragraph
putpdf text ("3 | How complete is the picture?"), bold font("`font_title'", `size_chapter', "`bnr_ink'")
putpdf paragraph
putpdf text ("Events identified through death records"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph
putpdf text ("Each tile gives the estimated additional DCO contribution as a percentage of the Primary national event estimate. The latest 15 complete years are shown. Green is lower reliance, amber moderate and red higher; the displayed number remains the main information."), font("`font_body'", 8, "`bnr_muted'")
capture confirm file "`fig_e1'"
if !_rc {
    putpdf table e1_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e1_fig(1,1) = image("`fig_e1'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e1_note = (2,1), width(100%) border(all, nil)
putpdf table e1_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e1_note(2,1) = ("`ann_evt_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e1_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Reliance on Possible deaths"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph
putpdf text ("Possible-only deaths as a percentage of the Inclusive annual mortality count. Green is lower reliance, amber moderate and red higher; the percentage remains the main information."), font("`font_body'", 8, "`bnr_muted'")
capture confirm file "`fig_e2'"
if !_rc {
    putpdf table e2_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e2_fig(1,1) = image("`fig_e2'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e2_note = (2,1), width(100%) border(all, nil)
putpdf table e2_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e2_note(2,1) = ("`ann_mort_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e2_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")


* -----------------------------------------------------------------------------
* 19. Methods - what we did and what the numbers mean
* -----------------------------------------------------------------------------

* METHODS CHAPTER - CONTROLLED STANDARD TEXT.
* BNR ANALYST: do not casually edit definitions, equations or governance text.
* This section explains the established public workflow; it does not execute
* the underlying event, mortality, rate, suppression or approval methods.
* Material amendments require methods and governance review, not annual copy
* editing alone.

putpdf pagebreak
putpdf paragraph
putpdf text ("4 | Methods"), bold font("`font_title'", `size_chapter', "`bnr_ink'")
putpdf paragraph
putpdf text ("Scope, definitions and event ascertainment"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("`annual_methods_note'"), font("`font_body'", 8.5)

putpdf paragraph
putpdf text ("Surveillance population and unit of analysis"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The CVD-event series counts eligible cardiovascular events among Barbados residents, not unique people. A person may contribute more than one eligible event when each event meets the approved event definition. The annual standard section reports All CVD and the two component families Heart and Stroke, together with sex and broad age summaries where those dimensions are present in the approved public release."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Event classification"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Records enter the event series only after the approved CVD-event, residence, reporting-period and duplicate-resolution rules have been applied. Hospital-recorded statistics use eligible events identified from hospital information. The Queen Elizabeth Hospital is Barbados's only tertiary hospital, so this series provides an important view of serious recognised CVD events, but it is not treated as complete national ascertainment."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Death-certificate-only ascertainment"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A death-certificate-only (DCO) event is an eligible event identified from death information without a matching eligible hospital-recorded event. The controlled event workflow applies deterministic linkage and approved event-window rules before producing aggregate DCO-enhanced outputs. Hospital + DCO statistics are annual only. Where linkage remains unresolved, the public release carries a central aggregate estimate and separate lower and upper linkage values; this report displays those released quantities and does not reconstruct them."), font("`font_body'", 8.4)

putpdf table event_scope = (3,3), width(100%) border(all, nil)
putpdf table event_scope(1,1) = ("Published event series")
putpdf table event_scope(1,2) = ("Source coverage")
putpdf table event_scope(1,3) = ("Interpretation")
putpdf table event_scope(2,1) = ("Hospital-recorded")
putpdf table event_scope(2,2) = ("Eligible hospital events")
putpdf table event_scope(2,3) = ("Observed serious CVD events recorded through the hospital source")
putpdf table event_scope(3,1) = ("Hospital + DCO")
putpdf table event_scope(3,2) = ("Hospital events plus eligible DCO contribution")
putpdf table event_scope(3,3) = ("Broader annual national estimate, with linkage uncertainty reported separately")
putpdf table event_scope(.,.), font("`font_body'", 7.8)
putpdf table event_scope(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table event_scope(.,1), bold


putpdf pagebreak
putpdf paragraph
putpdf text ("Mortality case ascertainment"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("BNR mortality surveillance uses death-certificate information to create a consistent practical cardiovascular classification when a formally assigned national underlying cause of death is not available to the Registry for routine surveillance. The method considers the wording on the certificate, whether information appears in Part I or Part II, the order of lines in Part I, documented mortality-coding principles and the strength of the available cardiovascular evidence."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Evidence classes"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table mort_classes = (6,2), width(100%) border(all, nil)
putpdf table mort_classes(1,1) = ("Class")
putpdf table mort_classes(1,2) = ("BNR interpretation")
putpdf table mort_classes(2,1) = ("Clear")
putpdf table mort_classes(2,2) = ("Strong evidence that the death belongs in the relevant BNR cardiovascular mortality group.")
putpdf table mort_classes(3,1) = ("Likely")
putpdf table mort_classes(3,2) = ("Good evidence, although some uncertainty remains.")
putpdf table mort_classes(4,1) = ("Possible")
putpdf table mort_classes(4,2) = ("Cardiovascular attribution is plausible, but uncertainty is material.")
putpdf table mort_classes(5,1) = ("Mention only")
putpdf table mort_classes(5,2) = ("Relevant wording is present but does not support approximate underlying-cause attribution.")
putpdf table mort_classes(6,1) = ("No evidence")
putpdf table mort_classes(6,2) = ("No qualifying cardiovascular evidence is identified by the approved rules.")
putpdf table mort_classes(.,.), font("`font_body'", 7.8)
putpdf table mort_classes(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table mort_classes(.,1), bold

putpdf paragraph
putpdf text ("Primary and Inclusive mortality definitions"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Primary includes Clear + Likely classifications. Inclusive includes Clear + Likely + Possible. Inclusive therefore contains Primary. The two are alternative classification-sensitivity definitions and must not be added together. Their difference is not a statistical confidence interval."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Relation to official cause-of-death statistics"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The BNR method is a structured surveillance classification. It is not full ICD-10 underlying-cause coding and should not be assumed to be directly equivalent to official national or international cause-of-death series that use formal underlying-cause selection and coding rules."), font("`font_body'", 8.4)



putpdf pagebreak
putpdf paragraph
putpdf text ("Measures, rates and uncertainty"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Counts and percentages"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Counts are registry enumerations of eligible events or classified deaths. Percentage distributions describe how a published total is divided across groups; they are not population risks. The DCO-reliance and Possible-death percentages used in this report are presentation summaries of already-published aggregate counts."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Crude rate"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table eq_crude = (1,1), width(86%) border(all, nil) halign(center)
putpdf table eq_crude(1,1) = ("Rate per 100,000 = eligible events or deaths / resident population x 100,000"), ///
    bold font("`font_body_med'", 9, "`bnr_teal'") bgcolor("`bnr_pale2'")
putpdf paragraph
putpdf text ("The matching resident population denominator is taken from the approved UN World Population Prospects 2024 Barbados series carried by the public workflow."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Direct age standardisation"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table eq_asr = (1,1), width(86%) border(all, nil) halign(center)
putpdf table eq_asr(1,1) = ("Age-standardised rate = sum of age-specific rate x standard-population weight"), ///
    bold font("`font_body_med'", 9, "`bnr_teal'") bgcolor("`bnr_pale2'")
putpdf paragraph
putpdf text ("BNR uses the WHO World Standard Population 2000-2025 where age-standardised rates are specified. Standardisation reduces differences caused only by differing age structures; it does not remove uncertainty from ascertainment, classification or small numbers."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Statistical confidence intervals"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Published crude-rate intervals use the exact Poisson (Garwood) method where specified. Published directly age-standardised mortality intervals use the Fay-Feuer gamma method. Event-rate outputs carry the interval method supplied by the approved release. The annual report reads the released limits rather than recalculating them."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("DCO linkage uncertainty"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Hospital + DCO annual event counts and event rates may carry separate lower and upper linkage values. These describe uncertainty from DCO ascertainment and linkage. They answer a different question from a statistical confidence interval, so the report shows linkage uncertainty as a pale band and statistical uncertainty as whiskers rather than combining them into one range."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Comparators"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Annual counts use the published mean for the same stratum over the previous five calendar years. Quarterly counts may use the published mean for the same quarter in the previous five years. The fixed 2015-2019 monthly historical reference used in dashboard and rolling-update products is a separate seasonal reference and is not a confidence interval or a rolling annual comparator."), font("`font_body'", 8.4)

putpdf pagebreak
putpdf paragraph
putpdf text ("Completeness, disclosure and publication governance"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Completeness and reporting period"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The standard annual section uses complete annual observations. Public releases may also contain monthly or quarterly rows, including a current incomplete quarter or year for operational dashboards. Those rows are not treated as complete annual results. Release date and latest observation period are separate concepts and should not be interpreted as the same date."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Disclosure control"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("BNR publishes aggregate statistics rather than patient-level records. Positive counts below six are normally subject to primary suppression. Secondary suppression is then used when row, column or related totals could otherwise allow a protected value to be inferred. Overly detailed combinations are avoided, and every public release passes disclosure-control review before publication. A protected value is not zero and this annual report never reconstructs it from related cells."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("From source data to this report"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table workflow = (5,2), width(100%) border(all, nil)
putpdf table workflow(1,1) = ("1  PREPARE")
putpdf table workflow(1,2) = ("Versioned source releases and controlled analytical inputs are prepared.")
putpdf table workflow(2,1) = ("2  CALCULATE")
putpdf table workflow(2,2) = ("Readable Stata programs create the approved surveillance measures and structured outputs.")
putpdf table workflow(3,1) = ("3  REVIEW")
putpdf table workflow(3,2) = ("Automated QA and disclosure checks prepare a fixed candidate for human review.")
putpdf table workflow(4,1) = ("4  APPROVE")
putpdf table workflow(4,2) = ("Authorised reviewers assess analytical plausibility, disclosure safety and publication readiness.")
putpdf table workflow(5,1) = ("5  PUBLISH")
putpdf table workflow(5,2) = ("Only approved public products are promoted to the Information Hub; the annual report reads those declared public products.")
putpdf table workflow(.,1), bold font("`font_title'", 8, "`bnr_teal'")
putpdf table workflow(.,2), font("`font_body'", 8)

* -----------------------------------------------------------------------------
* 17. E3/E4 Data availability and understanding uncertainty
* -----------------------------------------------------------------------------

* CHAPTER 3 - INVARIANT EXPLANATORY CONTENT.
* This block reports the available complete-year spans and distinguishes
* statistical confidence intervals from DCO linkage uncertainty. It must not
* merge the two interval concepts or imply that Primary/Inclusive differences
* are statistical confidence limits.

putpdf pagebreak
putpdf paragraph
putpdf text ("Data availability"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("The standard annual report uses complete published annual observations only. The latest release can contain partial monthly or quarterly periods that are appropriate for dashboards and rolling updates but are not treated as complete annual results here."), font("`font_body'", 9)

local event_first "-"
local event_last "-"
local mort_first "-"
local mort_last "-"
use "`annual_event_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "CVD-BURDEN-001", meanonly
if r(N) > 0 {
    local event_first = string(r(min), "%4.0f")
    local event_last = string(r(max), "%4.0f")
}
use "`annual_mortality_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "MORT-BURDEN-001", meanonly
if r(N) > 0 {
    local mort_first = string(r(min), "%4.0f")
    local mort_last = string(r(max), "%4.0f")
}
putpdf table availability = (3,4), width(100%) border(all, nil)
putpdf table availability(1,1) = ("Series")
putpdf table availability(1,2) = ("First complete annual year")
putpdf table availability(1,3) = ("Latest complete annual year")
putpdf table availability(1,4) = ("Release used")
putpdf table availability(2,1) = ("CVD events")
putpdf table availability(2,2) = ("`event_first'")
putpdf table availability(2,3) = ("`event_last'")
putpdf table availability(2,4) = ("`event_release'")
putpdf table availability(3,1) = ("CVD mortality")
putpdf table availability(3,2) = ("`mort_first'")
putpdf table availability(3,3) = ("`mort_last'")
putpdf table availability(3,4) = ("`mortality_release'")
putpdf table availability(.,.), font("`font_body'", 8)
putpdf table availability(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table availability(.,1), bold

putpdf paragraph
putpdf text ("Understanding uncertainty"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf table uncertainty = (3,3), width(100%) border(all, nil)
putpdf table uncertainty(1,1) = ("What is shown")
putpdf table uncertainty(1,2) = ("Visual form")
putpdf table uncertainty(1,3) = ("What it means")
putpdf table uncertainty(2,1) = ("Statistical 95% confidence interval")
putpdf table uncertainty(2,2) = ("Transparent shaded band")
putpdf table uncertainty(2,3) = ("Statistical uncertainty around the published estimate under its stated method.")
putpdf table uncertainty(3,1) = ("DCO linkage range")
putpdf table uncertainty(3,2) = ("Pale shaded band")
putpdf table uncertainty(3,3) = ("Uncertainty in the national event estimate arising from incomplete deterministic linkage of death records to hospital events.")
putpdf table uncertainty(1,.), bold bgcolor("`bnr_white'") font("`font_body'", 8) ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table uncertainty(2/3,.), font("`font_body'", 8)
putpdf paragraph
putpdf text ("The two intervals answer different questions and should not be combined into a single range. The report therefore gives them different visual forms."), bold font("`font_title'", 8.5, "`bnr_teal'")
