/*******************************************************************************
DO-FILE: bnr_report_annual_standard.do
VERSION: 2.5.1 (6 September 2026)
PURPOSE: Reusable putpdf composition for the standard annual CVD surveillance
         section.

CALLER:
  bnr_report_annual_s1_build.do only.

SOURCE BOUNDARY:
  This file reads only the two declared approved public release CSVs selected
  and checksum-validated by Step 1. It never reads confidential source data and
  it does not recalculate published surveillance rates.

DESIGN CONTRACT:
  - A4 portrait annual-report publication, not a printed dashboard.
  - Montserrat Medium is used for titling and Montserrat for body copy.
  - The UWI crest, restrained BNR palette and briefing-style white space provide
    the visual identity.
  - The cover and Year in Brief use fixed invisible-table layout grids so the
    page is composed deliberately rather than allowed to flow unpredictably.
  - Results graphics show the complete approved annual time series.
  - Exact result tables show the latest five complete years in wide form.
  - Public-facing headings use counts/events/deaths rather than "burden".
  - Graph furniture is deliberately sparse.
  - DCO/linkage uncertainty is shown as a pale band; published statistical
    confidence intervals are shown as whiskers.
  - Published five-year count comparators are used where they exist.
  - Interpretation remains analyst-owned in the year-specific interpretation
    file; this composition file does not generate editorial conclusions.
  - Special chapter composition remains outside this file.

DESIGN PASS 2.5.1:
  - Reserve one explicit front-matter page for the dynamic contents generated
    by the controlled PDF-finishing helper.
  - The placeholder is presentation metadata only. It contains no analytical
    information and must remain unique within the report body.

DESIGN PASS 2.2.0:
  - Keep summary-card backgrounds continuous behind labels and values.
  - Simplify interpretation callouts to one continuous pale panel.
  - Widen annual graphics, move legends to 12 o'clock, remove axis lines and
    add same-colour observed-value markers to line charts.
  - Increase use of published uncertainty without combining distinct sources:
    DCO linkage ranges are shaded; statistical 95% confidence intervals use
    whiskers.
  - Add a concise quarterly hospital-recorded "How the year unfolded" view.
  - Rebuild completeness graphics as labelled five-year tile matrices.
  - Expand Methods into a publication-grade technical section covering
    ascertainment, definitions, equations, uncertainty, disclosure and release
    governance.
  - Keep analytical definitions, release selection and workflow boundaries
    unchanged.

DESIGN PASS 2.4.0:
  - Rebuild the year-in-brief page as headline cards, one monthly event chart
    and three findings; remove the uninformative mini-trends and the separate
    quarterly page.
  - Round the four headline values and published confidence intervals to whole
    numbers for this high-level page.
  - Use explicit card spacer cells and white card surfaces with coloured top
    rules, avoiding putpdf's opaque text-background artefact.
  - Keep the disease-specific CVD, Heart and Stroke chapter expansion for the
    next design stage.

DESIGN PASS 2.5.0:
  - Replace combined subtype pages with a consistent All-CVD, Heart and Stroke
    sequence for counts, rates, women and men, and broad age patterns.
  - Apply the same disease-specific sequence to mortality, preserving Primary
    and Inclusive mortality definitions.
  - Keep all metric selection in an included, readable Stata section so the
    established annual workflow and publication boundary are unchanged.

DESIGN PASS 2.3.0:
  - Establish a single report type scale and a white-card, coloured-rule visual
    treatment that avoids opaque text-background artefacts in putpdf output.
  - Standardise metric strips, interpretation callouts and data-table headers
    around rules and whitespace rather than broad cell shading.
  - Page furniture is applied later by the Step 1 controlled PDF helper; it is
    deliberately outside this composition file and has no analytical role.
*******************************************************************************/

*******************************************************************************
* BNR ANALYST GUIDE - REUSABLE STANDARD SECTION
*
* BNR ANALYST: DO NOT EDIT THIS FILE for routine annual production.
* This is the invariant composition layer shared across reporting years. It
* selects already-published rows, draws the standard graphics and tables, and
* inserts analyst-owned narrative locals at predetermined positions. It must
* never read confidential data or become a second metric-calculation workflow.
*
* Safe annual narrative editing belongs in the year-specific interpretation
* DO file. A structural or graphical change here is a maintained template
* change: review it, build a new candidate version and inspect the whole PDF.
*
* IMPORTANT: the large `if 0 { ... }` block is disabled legacy reference code.
* Do not reactivate, edit, extract or reorder it during routine work.
*******************************************************************************

version 19.0

* -----------------------------------------------------------------------------
* 1. Required context and visual language
* -----------------------------------------------------------------------------
* INVARIANT TEMPLATE SETUP - DO NOT EDIT ROUTINELY.
* Confirm the user supplied a report year and two release IDs, require the
* crest, define the single palette/type scale, and create the private figures
* directory. These locals are reused by the standard and Special chapters.

if "`report_year4'" == "" {
    display as error "Annual standard composition requires local report_year4."
    exit 198
}
if "`event_release'" == "" | "`mortality_release'" == "" {
    display as error "Annual standard composition requires declared public release IDs."
    exit 198
}

local uwi_crest "$BNR_REPO/site/assets/images/uwi-crestonly-20p.png"
capture confirm file "`uwi_crest'"
if _rc {
    display as error "Required UWI crest not found: `uwi_crest'"
    exit 601
}

* RGB strings are retained as locals so the 2025 Special chapter can reuse them.
local bnr_ink       "44 62 80"
local bnr_teal      "4 81 116"
local bnr_primary   "43 115 136"
local bnr_secondary "91 139 151"
local bnr_women     "122 85 134"
local bnr_men       "45 103 141"
local bnr_stroke    "47 126 96"
local bnr_heart     "178 95 82"
local bnr_under70   "216 156 96"
local bnr_70plus    "122 135 148"
local bnr_pale      "240 246 248"
local bnr_pale2     "248 249 250"
local bnr_white     "255 255 255"
local bnr_rule      "222 226 230"
local bnr_muted     "102 102 102"
local bnr_green     "214 237 223"
local bnr_amber     "255 231 168"
local bnr_red       "243 198 204"
local bnr_green_text "0 128 70"
local bnr_amber_text "181 103 0"
local bnr_red_text   "190 0 32"

* Base CVD colour: 4 81 116
local bnr_women_all_cvd "4 116 161"     // lighter
local bnr_men_all_cvd   "4 46 71"       // darker

* Base Heart colour: 178 95 82
local bnr_women_heart "233 130 112" // lighter
local bnr_men_heart   "123 60 52"   // darker

* Base Stroke colour: 47 126 96
local bnr_women_stroke "72 171 131" // lighter
local bnr_men_stroke   "22 81 61"   // darker

* Publication typography. These fonts are part of the intended analytics
* environment. A separate report style sheet will be produced once the visual
* system has stabilised.
local font_title      "Montserrat Medium"
local font_body       "Montserrat"
local font_body_med   "Montserrat Medium"
local font_body_light "Montserrat Light"

* One reusable A4 type scale. Page-specific design may use these local names,
* but must not introduce a second heading hierarchy.
local size_chapter  18
local size_page     14
local size_section  11
local size_deck      8
local size_body      8.4
local size_table     7.8
local size_label     7.5
local size_value    14

local first_table_year = `report_year_num' - 4

capture mkdir "`candidate_dir'/figures"
local annual_figure_dir "`candidate_dir'/figures"

* -----------------------------------------------------------------------------
* 2. Read the two approved public releases once
* -----------------------------------------------------------------------------
* INVARIANT PUBLIC-DATA BOUNDARY - DO NOT EDIT.
* Import the two Step 1 checksum-validated public CSVs, convert only published
* numeric columns and cache them as temporary Stata datasets. No confidential
* source, linkage record or private analytical input may be introduced here.

tempfile annual_event_data annual_mortality_data

import delimited using "`event_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_month period_quarter period_complete value numerator denominator ///
        linkage_lower_value linkage_upper_value ci_lower_value ci_upper_value ///
        comparison_n {
    capture destring `v', replace force
}
save "`annual_event_data'", replace

import delimited using "`mortality_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_complete value numerator denominator ///
        ci_lower_value ci_upper_value comparison_n {
    capture destring `v', replace force
}
save "`annual_mortality_data'", replace

* -----------------------------------------------------------------------------
* 3. Latest-year values used on cover-summary cards
* -----------------------------------------------------------------------------
* INVARIANT METRIC SELECTION - DO NOT EDIT ROUTINELY.
* Select the four headline results and their released confidence limits. This
* block formats existing public values; it does not calculate surveillance
* rates. Changes to metric IDs, scopes, definitions or strata require formal
* template review because they alter the meaning of the summary page.

local yib_event_count "Not available"
local yib_event_rate "Not available"
local yib_event_rate_ci ""
local yib_death_count "Not available"
local yib_death_rate "Not available"
local yib_death_rate_ci ""

use "`annual_event_data'", clear
preserve
    keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_event_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "CVD-INCIDENCE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_event_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_event_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore
use "`annual_mortality_data'", clear
preserve
    keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        case_definition == "primary_clear_likely" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_death_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "MORT-RATE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        case_definition == "primary_clear_likely" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_death_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_death_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore



* -----------------------------------------------------------------------------
* 4. Plain cover
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION BLOCK - NOT A ROUTINE ANALYST EDIT.
* Compose the cover within one fixed invisible table so pagination is stable.
* Text or branding changes should be treated as report-template changes and
* checked against the finished, furniture-stamped PDF.

* The cover is held in one invisible layout grid. This avoids the page-flow
* behaviour of the first prototype, where each cover element could land on a
* separate page.

putpdf table cover = (5,1), width(15%) border(all, nil) halign(center)
putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = (" ")
putpdf table cover(4,1) = (" ")
putpdf table cover(5,1) = image("`uwi_crest'"), halign(center)

putpdf table cover = (8,12), width(88%) border(all, nil) halign(center)
putpdf table cover(1,1), colspan(12)
putpdf table cover(2,1), colspan(12)
putpdf table cover(3,1), colspan(12)
putpdf table cover(4,1), colspan(12)
putpdf table cover(5,1), colspan(12)
putpdf table cover(6,1), colspan(12)
putpdf table cover(7,1), colspan(12)
putpdf table cover(8,1), colspan(12)

putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = ("BARBADOS NATIONAL REGISTRY"), ///
    halign(center) font("`font_title'", 10, "`bnr_teal'")
putpdf table cover(4,1) = ("Annual cardiovascular disease report"), ///
    halign(center) bold font("`font_title'", 24, "`bnr_ink'")
putpdf table cover(5,1) = ("`report_year4'"), ///
    halign(center) bold font("`font_title'", 30, "`bnr_ink'")
putpdf table cover(6,1) = ("Cardiovascular disease events and mortality in Barbados"), ///
    halign(center) font("`font_body'", 11, "`bnr_muted'")
putpdf table cover(7,1) = (" ")
putpdf table cover(8,1) = ("The University of the West Indies | Cave Hill Campus"), ///
    halign(center) font("`font_body'", 8, "`bnr_muted'")



* -----------------------------------------------------------------------------
* 5A. Report information and front matter
* -----------------------------------------------------------------------------
* MAINTAINED FRONT-MATTER BLOCK.
* This page is public report metadata and explanatory context. Update authors,
* affiliations, acknowledgements and contact details when the report ownership
* changes. Do not alter the release identifiers or analytical definitions here.
*
* The report year, event release and mortality release are supplied by the
* controlled annual build workflow.

putpdf pagebreak

putpdf paragraph, font("`font_body'", 1)
putpdf text ("About this report"), ///
    bold font("`font_title'", 19, "`bnr_ink'") linebreak

putpdf text ("Annual cardiovascular disease report `report_year4'"), ///
    bold font("`font_title'", 11, "`bnr_teal'") linebreak

putpdf text ("Cardiovascular disease events and mortality in Barbados"), ///
    font("`font_body'", 9, "`bnr_muted'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Purpose and scope"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("This report provides an annual overview of cardiovascular disease events and mortality in Barbados. It presents results on the burden of heart attacks and strokes in Barbados, together with selected sex and age summaries. The report is publically available, and is particularly aimed at supporting decision-making by government, hospitals, clinics, public-health teams, researchers and other partners."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 2)

putpdf text ///
    ("The report presents a range of annual aggregated observations using the quality-controlled and approved BNR data releases. Estimates should be interpreted alongside the definitions, coverage notes and uncertainty information provided in the report. The report and the underlying data are available from the BNR Information Hub."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Report information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf table report_frontmatter = (6,2), width(100%) border(all, nil)

putpdf table report_frontmatter(1,1) = ("Report")
putpdf table report_frontmatter(1,2) = ///
    ("Annual cardiovascular disease report `report_year4'")

putpdf table report_frontmatter(2,1) = ("Prepared by")
putpdf table report_frontmatter(2,2) = ///
    ("Christina Howitt; Jacqueline Campbell; Ian Hambleton")

putpdf table report_frontmatter(3,1) = ("Institution")
putpdf table report_frontmatter(3,2) = ///
    ("Barbados National Registry | The University of the West Indies, Cave Hill Campus")

putpdf table report_frontmatter(4,1) = ("Approved data releases")
putpdf table report_frontmatter(4,2) = ///
    ("CVD events: `event_release' | CVD mortality: `mortality_release'")

putpdf table report_frontmatter(5,1) = ("Online report")
putpdf table report_frontmatter(5,2) = ///
    ("https://uwi-bnr.github.io/info-hub/")

putpdf table report_frontmatter(6,1) = ("Suggested citation")

putpdf table report_frontmatter(6,2) = ///
    ("Howitt C, Campbell J, Hambleton I for the Barbados National Registry. ")

putpdf table report_frontmatter(6,2) = ///
    ("Annual cardiovascular disease report `report_year4': cardiovascular disease events and mortality in Barbados. "), italic append

putpdf table report_frontmatter(6,2) = ///
    ("The University of the West Indies, Cave Hill Campus, Bridgetown, Barbados."), append

putpdf table report_frontmatter(.,.), ///
    font("`font_body'", 7.8, "`bnr_ink'") ///
    bgcolor("`bnr_white'")

putpdf table report_frontmatter(1,.), ///
    bold font("`font_title'", 7.8, "`bnr_teal'") ///
    border(top, single, "`bnr_teal'") ///
    border(bottom, single, "`bnr_rule'")

putpdf table report_frontmatter(2/6,1), ///
    bold font("`font_title'", 7.8, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Acknowledgements"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("The Barbados National Registry acknowledges the clinical, hospital, registry, data-management and public-health teams whose work supports the production of this surveillance report."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Further information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("Definitions, ascertainment rules, mortality classifications, uncertainty measures, data availability and disclosure controls are described in the BNR Methods manual, available online. These methods, latest public report and associated data products are available at: https://uwi-bnr.github.io/info-hub/"), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ///
    ("Publication note: This edition is produced through the controlled BNR annual-report build, approval and publication workflow. The public version is the approved version deposited through that workflow."), ///
    italic font("`font_body'", 7.4, "`bnr_muted'")

* -----------------------------------------------------------------------------
* 5B. Dynamic contents placeholder
* -----------------------------------------------------------------------------
* INVARIANT PRESENTATION HAND-OFF - DO NOT EDIT OR DUPLICATE.
* Stata owns the position of the Contents page. The controlled Python finishing
* helper replaces this complete page after it has identified the sections that
* actually exist in the rendered body PDF. The unique marker is deliberately
* unobtrusive because the unstamped body PDF remains private.

putpdf pagebreak
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Contents"), bold font("`font_title'", 19, "`bnr_ink'") linebreak
putpdf text ("BNR_TOC_PLACEHOLDER"), font("`font_body'", 1, "`bnr_white'")

* -----------------------------------------------------------------------------
* 5C. Year in brief - one-page visual summary
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION AND METRIC-SELECTION BLOCK.
* BNR ANALYST: do not change filters or calculations here. This block draws the
* approved monthly hospital-recorded series, lays out four headline cards and
* inserts three editable messages defined in the year interpretation file.

* Month-on-month CVD events.
* All years other than the report year are faded lines without dots.
* The current report year is overlaid as the prominent connected line.
* This automatically updates for future annual reports.

local yib_monthly_fig "`annual_figure_dir'/yib_monthly_events.png"
use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & ///
    period_type == "monthly" & ///
    event_type == "all_cvd" & ///
    sex == "all" & ///
    age_group == "all" & ///
    ascertainment_scope == "hospital_only" & ///
    statistic == "monthly_count" & ///
    period_complete == 1
quietly count

if r(N) >= 2 {
    sort period_year period_month

    * Create one variable for each historical year.
    * The current report year is excluded from these variables.
    separate value if period_year != `report_year_num', ///
        by(period_year) generate(yib_historical)

    * Create rolling comparator years 
    unab yib_historical_vars : yib_historical*
    local yib_historical_colours
    foreach v of local yib_historical_vars {
        local yib_historical_colours `"`yib_historical_colours' "`bnr_teal'%20""'
    }

    #delimit ; 
    twoway 
        (line yib_historical* period_month, sort lcolor(`yib_historical_colours') lwidth(thin)) 
        (connected value period_month if period_year == `report_year_num', sort 
            lcolor("`bnr_teal'") mcolor("`bnr_teal'") msymbol(O) msize(5) 
            lwidth(1))
            , 
		plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
		graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))
        xlabel(1 "Jan" 2 " " 3 " " 4 "Apr" 5 " " 6 " " 
               7 "Jul" 8 " " 9 " " 10 "Oct" 11 " " 12 " ",
               labsize(9) noticks nogrid)
        ylabel(#4, angle(horizontal) labsize(9) noticks nogrid) 
        xscale(noline range(0.5(1)12.5)) yscale(noline range(70(5)110)) 
        xtitle("") ytitle("", size(vsmall)) legend(off) 
        xsize(7.6) ysize(1.55)
        name(yib);
    #delimit cr 
    graph export "`yib_monthly_fig'", replace width(2600)
}

putpdf pagebreak
putpdf paragraph, font("`font_body'", 1)
putpdf text ("`report_year4' in brief"), bold font("`font_title'", 20, "`bnr_ink'") linebreak
putpdf text ("The latest complete year at a glance"), ///
    font("`font_body'", 9, "`bnr_muted'")

* Four explicit cards. Column 2 and row 4 are intentional spacer cells. White
* card surfaces eliminate putpdf's visible opaque text-background artefact.
putpdf table yib_cards = (7,3), width(100%) border(all, nil)
forvalues r = 1/7 {
    putpdf table yib_cards(`r',2) = ("")
}
putpdf table yib_cards(4,1) = (""), font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(4,3) = (""), font("`font_title'", 2.5, "`bnr_teal'")

putpdf table yib_cards(1,1) = ("CVD EVENTS"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,1) = ("`yib_event_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,1) = ("Primary national estimate"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(1,3) = ("CVD EVENT RATE"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,3) = ("`yib_event_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,3) = ("Age-standardised | `yib_event_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,1) = ("CVD DEATHS"), bold font("`font_title'", 7.5, "`bnr_heart'")
putpdf table yib_cards(6,1) = ("`yib_death_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,1) = ("Primary definition"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,3) = ("CVD MORTALITY RATE"), bold font("`font_title'", 7.5, "`bnr_secondary'")
putpdf table yib_cards(6,3) = ("`yib_death_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,3) = ("Age-standardised | `yib_death_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(.,.), bgcolor("`bnr_white'")
putpdf table yib_cards(1,1), border(top, single, "`bnr_teal'")
putpdf table yib_cards(1,3), border(top, single, "`bnr_teal'")
putpdf table yib_cards(5,1), border(top, single, "`bnr_heart'")
putpdf table yib_cards(5,3), border(top, single, "`bnr_secondary'")

putpdf paragraph, font("`font_body'", 1)
putpdf text ("How the year unfolded"), bold font("`font_title'", 10.5, "`bnr_ink'")
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Monthly hospital-recorded CVD events in `report_year4'. Unlike hospital events, national event estimates are updated annually because events captured only through death-record are added after each year closes."), font("`font_body'", 7.4, "`bnr_muted'")
capture confirm file "`yib_monthly_fig'"
if !_rc {
    putpdf table yib_monthly = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table yib_monthly(1,1) = image("`yib_monthly_fig'")
}

putpdf paragraph, font("`font_body'", 1)
putpdf text ("What stood out in `report_year4'?"), ///
    bold font("`font_title'", 10.5, "`bnr_ink'")

putpdf table yib_messages = (4,12), width(100%) border(all, nil)
forvalues rr = 1/4 {
    putpdf table yib_messages(`rr',1)
    putpdf table yib_messages(`rr',2), colspan(11)
    putpdf table yib_messages(`rr',1) = ("0`rr'"), ///
        halign(center) bold font("`font_title'", 9, "`bnr_teal'")
}
putpdf table yib_messages(1,2) = ("`annual_summary_message_1'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(2,2) = ("`annual_summary_message_2'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(3,2) = ("`annual_summary_message_3'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(4,2) = ("`annual_summary_message_4'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")




* -----------------------------------------------------------------------------
* 6. Stage 3 disease-specific event and mortality sections
* -----------------------------------------------------------------------------

* INVARIANT INCLUDE POINT - DO NOT MOVE.
* The included template creates all live Chapter 1 and Chapter 2 pages in this
* position. Its internal comments identify each graphic, table and narrative
* hook. Moving the include changes report order and page flow.

include "$BNR_REPO/scripts/stata/reporting/templates/bnr_report_annual_stage3_sections.do"



* -----------------------------------------------------------------------------
* 16. How complete is the picture? - E1/E2 quality matrices
* -----------------------------------------------------------------------------

* CHAPTER 3 - MAINTAINED QUALITY PRESENTATION.
* BNR ANALYST: the graphics may be refined only as an approved template change.
* Do not change the public metrics or definitions. The first matrix describes
* the published DCO contribution to Primary national event estimates; the
* second describes reliance on Possible deaths within Inclusive mortality.
* Percentages are presentation summaries of released aggregate counts.

local fig_e1 "`annual_figure_dir'/quality_event_dco.png"
local fig_e2 "`annual_figure_dir'/quality_possible_deaths.png"
local quality_first_year = `report_year_num' - 14

use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    ((ascertainment_scope == "additional_dco" & mortality_definition == "primary") | ///
     (ascertainment_scope == "hospital_plus_dco" & mortality_definition == "primary"))
keep period_year event_type ascertainment_scope value
reshape wide value, i(period_year event_type) j(ascertainment_scope) string
gen double quality_pct = 100 * valueadditional_dco / valuehospital_plus_dco
gen byte quality_band = cond(quality_pct < 10, 1, cond(quality_pct < 15, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)

local x_range_min = `quality_first_year' - 1 
local x_range_max = `report_year_num' + 1

if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_mort)
      ;
    #delimit cr
    graph export "`fig_e1'", replace width(2800)
}

use "`annual_mortality_data'", clear
keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    inlist(case_definition, "primary_clear_likely", "upper_clear_likely_possible")
keep period_year event_type case_definition value
reshape wide value, i(period_year event_type) j(case_definition) string
gen double quality_pct = 100 * ///
    (valueupper_clear_likely_possible - valueprimary_clear_likely) / ///
    valueupper_clear_likely_possible
gen byte quality_band = cond(quality_pct < 20, 1, cond(quality_pct < 30, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)
if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_dco)
      ;
    #delimit cr
    graph export "`fig_e2'", replace width(2800)
}

putpdf pagebreak
putpdf paragraph
putpdf text ("3 | How complete is the picture?"), bold font("`font_title'", `size_chapter', "`bnr_ink'")
putpdf paragraph
putpdf text ("Events identified through death records"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph

putpdf text ("Each tile gives the estimated additional DCO contribution as a percentage of the Primary national event estimate. The latest 15 complete years are shown. "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("Green "), bold font("`font_body'", 8, "`bnr_green_text'")
putpdf text ("is lower reliance, "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("amber "), font("`font_body'", 8, "`bnr_amber_text'")
putpdf text ("moderate "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("and "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("red "), font("`font_body'", 8, "`bnr_red_text'")
putpdf text ("higher."), font("`font_body'", 8, "`bnr_muted'")


capture confirm file "`fig_e1'"
if !_rc {
    putpdf table e1_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e1_fig(1,1) = image("`fig_e1'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e1_note = (2,1), width(100%) border(all, nil)
putpdf table e1_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e1_note(2,1) = ("`ann_evt_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e1_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Reliance on Possible deaths"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph
putpdf text ("Possible-only deaths as a percentage of the Inclusive annual mortality count. Green is lower reliance, amber moderate and red higher; the percentage remains the main information."), font("`font_body'", 8, "`bnr_muted'")
capture confirm file "`fig_e2'"
if !_rc {
    putpdf table e2_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e2_fig(1,1) = image("`fig_e2'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e2_note = (2,1), width(100%) border(all, nil)
putpdf table e2_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e2_note(2,1) = ("`ann_mort_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e2_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")


* -----------------------------------------------------------------------------
* 19. Methods - what we did and what the numbers mean
* -----------------------------------------------------------------------------

* METHODS CHAPTER - CONTROLLED STANDARD TEXT.
* BNR ANALYST: do not casually edit definitions, equations or governance text.
* This section explains the established public workflow; it does not execute
* the underlying event, mortality, rate, suppression or approval methods.
* Material amendments require methods and governance review, not annual copy
* editing alone.

putpdf pagebreak
putpdf paragraph
putpdf text ("4 | Methods"), bold font("`font_title'", `size_chapter', "`bnr_ink'")

* These are temporary web addresses. Keeping the common root in one local
* means the final address can be updated once without searching this chapter.
local methods_url_root      "https://uwi-bnr.github.io/info-hub"
local methods_url_public    "`methods_url_root'/methods/"
local methods_url_operations "`methods_url_root'/operations/"
local methods_url_technical "`methods_url_root'/technical/"

* Convert release IDs ending in YYYY_MM into a short readable date while
* retaining the exact release ID required for reproducibility.
local methods_months "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"
local event_release_display "`event_release'"
if regexm("`event_release'", "_[0-9][0-9][0-9][0-9]_[0-9][0-9]$") {
    local event_release_year = substr("`event_release'", strlen("`event_release'") - 6, 4)
    local event_release_month_n = real(substr("`event_release'", strlen("`event_release'") - 1, 2))
    if inrange(`event_release_month_n', 1, 12) {
        local event_release_month : word `event_release_month_n' of `methods_months'
        local event_release_display "`event_release' (`event_release_year', `event_release_month')"
    }
}

local mortality_release_display "`mortality_release'"
if regexm("`mortality_release'", "_[0-9][0-9][0-9][0-9]_[0-9][0-9]$") {
    local mortality_release_year = substr("`mortality_release'", strlen("`mortality_release'") - 6, 4)
    local mortality_release_month_n = real(substr("`mortality_release'", strlen("`mortality_release'") - 1, 2))
    if inrange(`mortality_release_month_n', 1, 12) {
        local mortality_release_month : word `mortality_release_month_n' of `methods_months'
        local mortality_release_display "`mortality_release' (`mortality_release_year', `mortality_release_month')"
    }
}

putpdf paragraph
putpdf text ("What this report measures"), bold font("`font_title'", 14, "`bnr_ink'")

* Opening message card: this is the enduring public rationale for the methods.
putpdf table methods_opening_card = (2,1), width(100%) border(all, nil)
putpdf table methods_opening_card(1,1) = ("WHY THESE METHODS MATTER"), ///
    bold font("`font_title'", 8.4, "`bnr_teal'")
putpdf table methods_opening_card(2,1) = ///
    ("National surveillance brings together information recorded for different purposes, at different times and in different settings. The BNR applies consistent clinical, residency, timing, linkage and quality rules so these records can support a coherent national picture. Each published result can be traced to an approved data release and is accompanied by clear information about its coverage, uncertainty and confidentiality."), ///
    font("`font_body'", 8.4, "`bnr_teal'")
putpdf table methods_opening_card(1,1), border(top, single, "`bnr_teal'")
putpdf table methods_opening_card(2,1), border(bottom, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Data used for this report"), bold font("`font_title'", 14, "`bnr_ink'")

local event_first "-"
local event_last "-"
local mort_first "-"
local mort_last "-"
use "`annual_event_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "CVD-BURDEN-001", meanonly
if r(N) > 0 {
    local event_first = string(r(min), "%4.0f")
    local event_last = string(r(max), "%4.0f")
}
use "`annual_mortality_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "MORT-BURDEN-001", meanonly
if r(N) > 0 {
    local mort_first = string(r(min), "%4.0f")
    local mort_last = string(r(max), "%4.0f")
}
putpdf table availability = (3,3), width(100%) border(all, nil)
putpdf table availability(1,1) = ("Series")
putpdf table availability(1,2) = ("Complete annual coverage")
putpdf table availability(1,3) = ("Public data release used")
putpdf table availability(2,1) = ("CVD events")
putpdf table availability(2,2) = ("`event_first' to `event_last'")
putpdf table availability(2,3) = ("`event_release_display'")
putpdf table availability(3,1) = ("CVD mortality")
putpdf table availability(3,2) = ("`mort_first' to `mort_last'")
putpdf table availability(3,3) = ("`mortality_release_display'")
putpdf table availability(.,.), font("`font_body'", 8)
putpdf table availability(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table availability(.,1), bold

putpdf paragraph
putpdf text ("Population, period and unit of analysis"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("This report describes eligible cardiovascular events and classified deaths among Barbados residents. Each event statistic counts eligible event episodes, so one person can contribute more than one event over time. Mortality statistics count deaths meeting the stated BNR evidence definition."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("The main results cover complete calendar years from January to December. The monthly "), font("`font_body'", 8.4)
putpdf text ("How the year unfolded "), italic font("`font_body'", 8.4)
putpdf text ("chart provides the one within-year view. Monthly and quarterly event results describe hospital-recorded events; broader national estimates incorporating death records are completed annually."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("A guide to the results"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_metric_map = (5,3), width(100%) border(all, nil)
putpdf table methods_metric_map(1,1) = ("Result")
putpdf table methods_metric_map(1,2) = ("What it describes")
putpdf table methods_metric_map(1,3) = ("Main information source")
putpdf table methods_metric_map(2,1) = ("Events")
putpdf table methods_metric_map(2,2) = ("Eligible Heart and Stroke event episodes")
putpdf table methods_metric_map(2,3) = ("Hospital records, extended annually with eligible death records")
putpdf table methods_metric_map(3,1) = ("Deaths")
putpdf table methods_metric_map(3,2) = ("Deaths meeting a stated BNR cardiovascular evidence definition")
putpdf table methods_metric_map(3,3) = ("Death-certificate information")
putpdf table methods_metric_map(4,1) = ("Population rates")
putpdf table methods_metric_map(4,2) = ("Events or deaths in relation to the corresponding resident population")
putpdf table methods_metric_map(4,3) = ("Approved releases and population estimates")
putpdf table methods_metric_map(5,1) = ("Quality indicators")
putpdf table methods_metric_map(5,2) = ("How much selected results depend on additional or less-certain information")
putpdf table methods_metric_map(5,3) = ("Approved public-release summaries")
putpdf table methods_metric_map(.,.), font("`font_body'", 7.3)
putpdf table methods_metric_map(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_metric_map(2/5,1), bold



** NEW METHODS PAGE. How CVD events are identified
putpdf pagebreak
putpdf paragraph
putpdf text ("How CVD events are identified"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("The BNR applies the same sequence of clinical, residency, timing and episode rules to every potential event. This turns information collected through routine care into a consistent surveillance series and supports fairer comparison over time."), font("`font_body'", 8.4)

* A ruled teal callout gives the comparability statement prominence without
* relying on bold text alone or on cell shading.
putpdf table methods_comparability_card = (2,1), width(100%) border(all, nil)
putpdf table methods_comparability_card(1,1) = ("COMPARING RESULTS OVER TIME"), ///
    bold font("`font_title'", 8.4, "`bnr_teal'")
putpdf table methods_comparability_card(2,1) = ///
    ("The complete series in this report can be compared consistently from 2010 onwards. The method was revised in 2025, so comparisons with earlier years should use the historical series reproduced in this report rather than estimates printed in reports from 2023 or earlier."), ///
    font("`font_body'", 8.4, "`bnr_teal'")
putpdf table methods_comparability_card(1,1), border(top, single, "`bnr_teal'")
putpdf table methods_comparability_card(2,1), border(bottom, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Heart, Stroke and All CVD"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Each eligible event is assigned to Heart or Stroke under the maintained BNR rules. All CVD is the reporting aggregate formed by combining those two event groups."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Heart and Stroke event definitions"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The clinical definition is the starting point. Residency, event date and episode rules then establish whether, when and how an eligible event contributes to the published series."), font("`font_body'", 8.4)

putpdf table methods_event_families = (3,2), width(100%) border(all, nil)
putpdf table methods_event_families(1,1) = ("Reporting family")
putpdf table methods_event_families(1,2) = ("What it represents")
putpdf table methods_event_families(2,1) = ("Heart")
putpdf table methods_event_families(2,2) = ///
    ("Eligible acute myocardial infarction events, generally corresponding to ICD-10 I21-I22, confirmed under BNR clinical and validation rules.")
putpdf table methods_event_families(3,1) = ("Stroke")
putpdf table methods_event_families(3,2) = ///
    ("Eligible acute stroke events, generally corresponding to ICD-10 I60-I64, confirmed under BNR clinical and validation rules.")
putpdf table methods_event_families(.,.), font("`font_body'", 7.5)
putpdf table methods_event_families(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_event_families(2/3,1), bold

putpdf table methods_event_rules = (6,2), width(100%) border(all, nil)
putpdf table methods_event_rules(1,1) = ("Decision")
putpdf table methods_event_rules(1,2) = ("What the rule achieves")
putpdf table methods_event_rules(2,1) = ("Disease definition")
putpdf table methods_event_rules(2,2) = ("Confirms that the clinical evidence meets the approved Heart or Stroke definition.")
putpdf table methods_event_rules(3,1) = ("Residence")
putpdf table methods_event_rules(3,2) = ("Restricts the series to people resident in Barbados for at least six months of the relevant calendar year.")
putpdf table methods_event_rules(4,1) = ("Event date")
putpdf table methods_event_rules(4,2) = ("Places the event in the correct reporting period using the approved date hierarchy.")
putpdf table methods_event_rules(5,1) = ("Event episode")
putpdf table methods_event_rules(5,2) = ("Brings together records that describe the same clinical episode before counting.")
putpdf table methods_event_rules(6,1) = ("Repeat event")
putpdf table methods_event_rules(6,2) = ("Allows a later eligible event to contribute a new count when it occurs outside the 28-day event window.")
putpdf table methods_event_rules(.,.), font("`font_body'", 7.7)
putpdf table methods_event_rules(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_event_rules(2/6,1), bold

putpdf paragraph
putpdf text ("Events and people"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Each count represents an event episode. Records occurring within the 28-day event window are treated as part of the same episode. A later eligible event can contribute another count, so one person may contribute more than one event over time."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Hospital-recorded ascertainment"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Hospital-recorded statistics use eligible events identified from hospital information. As Barbados's only tertiary hospital, the Queen Elizabeth Hospital provides an important view of serious recognised CVD events. Access to care, referral, diagnosis and recording all shape this view. The annual national reporting estimates extend it with eligible events identified through death records, as described next."), font("`font_body'", 8.4)



** NEW METHODS PAGE. Extending the picture using death records
putpdf pagebreak
putpdf paragraph
putpdf text ("Extending the picture using death records"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("Some eligible cardiovascular events are identified through death information rather than hospital records. Bringing the two sources together broadens the national picture and requires careful classification and matching so that an event already represented in the hospital series is counted appropriately."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("What is a DCO event?"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A death-certificate-only (DCO) event is an eligible event identified from death information with no matched eligible hospital-recorded event. DCO-enhanced counts and rates are produced annually, after death-record ascertainment for the year is complete. Annual aggregation also supports safe reporting where monthly or quarterly DCO numbers may be small. Monthly and quarterly event views therefore describe hospital-recorded events."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("How linkage is undertaken"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_linkage = (5,2), width(100%) border(all, nil)
putpdf table methods_linkage(1,1) = ("Stage")
putpdf table methods_linkage(1,2) = ("Plain-language description")
putpdf table methods_linkage(2,1) = ("1  Prepare")
putpdf table methods_linkage(2,2) = ///
    ("We prepare the hospital records and relevant death records for secure comparison.")
putpdf table methods_linkage(3,1) = ("2  Match")
putpdf table methods_linkage(3,2) = ///
    ("We compare records using approved combinations of names, dates and other identifying details, starting with the clearest matches.")
putpdf table methods_linkage(4,1) = ("3  Resolve")
putpdf table methods_linkage(4,2) = ///
    ("We accept clear matches and retain the uncertainty where the available information supports more than one interpretation.")
putpdf table methods_linkage(5,1) = ("4  Aggregate")
putpdf table methods_linkage(5,2) = ///
    ("We use the resolved links to produce anonymous aggregate event estimates for publication.")
putpdf table methods_linkage(.,.), font("`font_body'", 7.6)
putpdf table methods_linkage(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_linkage(2/5,1), bold font("`font_title'", 7.6, "`bnr_teal'")

putpdf paragraph
putpdf text ("Three published views of CVD events"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table event_scope = (4,3), width(100%) border(all, nil)
putpdf table event_scope(1,1) = ("Published series")
putpdf table event_scope(1,2) = ("Information included")
putpdf table event_scope(1,3) = ("How to use it")
putpdf table event_scope(2,1) = ("Hospital-recorded")
putpdf table event_scope(2,2) = ("Eligible hospital events")
putpdf table event_scope(2,3) = ("Shows recognised serious events recorded through the hospital source")
putpdf table event_scope(3,1) = ("Primary national")
putpdf table event_scope(3,2) = ("Hospital events plus DCO contribution based on Clear + Likely mortality evidence")
putpdf table event_scope(3,3) = ("Provides the main BNR annual national estimate")
putpdf table event_scope(4,1) = ("Inclusive national")
putpdf table event_scope(4,2) = ("Hospital events plus DCO contribution that also includes Possible mortality evidence")
putpdf table event_scope(4,3) = ("Provides a broader estimate showing sensitivity to the wider evidence definition")
putpdf table event_scope(.,.), font("`font_body'", 7.4)
putpdf table event_scope(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table event_scope(2/4,1), bold

putpdf paragraph
putpdf text ("Linkage uncertainty range"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Where unresolved links could affect the national total, the public data provide three values. The lower value uses the more conservative interpretation, the central value is the main BNR estimate, and the upper value reflects the broader contribution supported by the approved linkage rules. Together they show how much the national estimate could change under the accepted interpretations of unresolved matches. Because the DCO contribution is estimated at aggregate level, national event estimates may contain decimal values before rounding for presentation."), font("`font_body'", 8.2)

putpdf table methods_linkage_note = (1,1), width(100%) border(all, nil)
putpdf table methods_linkage_note(1,1) = ("WHEN READING THE REPORT | A wider linkage range means that unresolved matching has more influence on the national estimate. Statistical confidence intervals describe the precision of a rate and answer a different question."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_linkage_note(1,1), border(top, single, "`bnr_teal'")



** NEW METHODS PAGE. How CVD deaths are classified
putpdf pagebreak
putpdf paragraph
putpdf text ("How CVD deaths are classified"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("BNR mortality surveillance uses death-certificate information to create a consistent cardiovascular classification for routine surveillance. A formally coded national underlying cause of death is not currently available to the Registry for this purpose. Because certificates are received in paper form, the BNR first transcribes them into a standard electronic format on behalf of the Government, allowing every certificate to be assessed consistently."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("How the certificate is interpreted"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A cardiovascular term is interpreted in the context of the full certificate before a BNR classification is assigned. We consider the wording, whether it appears in Part I or Part II, the order of conditions in Part I, relevant mortality-coding principles and the strength of the supporting evidence. Part I records the sequence leading directly to death, while Part II records other contributing conditions. These details provide the context for assigning each death to one of five evidence classes."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Evidence classes"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table mort_classes = (6,3), width(100%) border(all, nil)
putpdf table mort_classes(1,1) = ("Class")
putpdf table mort_classes(1,2) = ("What the evidence means")
putpdf table mort_classes(1,3) = ("Use in published definitions")
putpdf table mort_classes(2,1) = ("Clear")
putpdf table mort_classes(2,2) = ("Strong evidence for the relevant cardiovascular mortality group")
putpdf table mort_classes(2,3) = ("Primary and Inclusive")
putpdf table mort_classes(3,1) = ("Likely")
putpdf table mort_classes(3,2) = ("Good cardiovascular evidence with some remaining uncertainty")
putpdf table mort_classes(3,3) = ("Primary and Inclusive")
putpdf table mort_classes(4,1) = ("Possible")
putpdf table mort_classes(4,2) = ("Plausible cardiovascular evidence with material uncertainty")
putpdf table mort_classes(4,3) = ("Inclusive")
putpdf table mort_classes(5,1) = ("Mention only")
putpdf table mort_classes(5,2) = ("Relevant wording recorded as contextual evidence")
putpdf table mort_classes(5,3) = ("Classification record")
putpdf table mort_classes(6,1) = ("No evidence")
putpdf table mort_classes(6,2) = ("The approved rules identify no qualifying cardiovascular evidence")
putpdf table mort_classes(6,3) = ("Classification record")
putpdf table mort_classes(.,.), font("`font_body'", 7.4)
putpdf table mort_classes(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table mort_classes(.,1), bold

putpdf paragraph
putpdf text ("Heart, Stroke and All CVD"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Heart includes qualifying ischaemic and coronary heart-disease evidence, including certificates that use terms other than 'heart attack'. Stroke includes qualifying acute ischaemic stroke and non-traumatic cerebral haemorrhage patterns. Each qualifying death is resolved to Heart or Stroke under the maintained hierarchy. All CVD is the reporting aggregate formed by combining those two groups."), font("`font_body'", 8.2)

putpdf paragraph
putpdf text ("Primary and Inclusive definitions"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Primary combines Clear and Likely evidence and is the main BNR mortality series. Inclusive contains the Primary series and additionally includes Possible cardiovascular deaths. The distance between them shows how sensitive the reported burden is to including this less-certain evidence."), font("`font_body'", 8.2)

putpdf paragraph
putpdf text ("Relation to official cause-of-death statistics"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Official cause-of-death statistics use the full international process for selecting and coding an ICD-10 underlying cause. The BNR uses a maintained death-certificate evidence classification to provide consistent and timely cardiovascular surveillance. The two series serve related but distinct purposes, so comparisons should take their different methods into account."), font("`font_body'", 8.2)

putpdf table methods_mort_note = (1,1), width(100%) border(all, nil)
putpdf table methods_mort_note(1,1) = ///
    ("WHEN READING THE REPORT | Read Primary and Inclusive as alternative views of the same mortality burden. Primary is the main series; Inclusive shows how the result changes when Possible cardiovascular deaths are included."), ///
    font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_mort_note(1,1), ///
    border(top, single, "`bnr_teal'")



** NEW METHODS PAGE. How the report measures CVD
putpdf pagebreak
putpdf paragraph
putpdf text ("How the report measures CVD"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("The report uses four complementary ways to describe CVD burden. Each answers a different question, so the measure and its denominator should always be read together."), font("`font_body'", 8.4)

putpdf table methods_measure_guide = (5,3), width(100%) border(all, nil)
putpdf table methods_measure_guide(1,1) = ("Measure")
putpdf table methods_measure_guide(1,2) = ("Question it answers")
putpdf table methods_measure_guide(1,3) = ("Best used for")
putpdf table methods_measure_guide(2,1) = ("Count")
putpdf table methods_measure_guide(2,2) = ("How many eligible events or classified deaths were recorded?")
putpdf table methods_measure_guide(2,3) = ("Describing the volume of events or deaths")
putpdf table methods_measure_guide(3,1) = ("Percentage")
putpdf table methods_measure_guide(3,2) = ("What share of a defined total belongs to a particular group?")
putpdf table methods_measure_guide(3,3) = ("Describing the composition of that total")
putpdf table methods_measure_guide(4,1) = ("Crude rate")
putpdf table methods_measure_guide(4,2) = ("How frequent was the outcome in the population during that year?")
putpdf table methods_measure_guide(4,3) = ("Describing the population's observed experience")
putpdf table methods_measure_guide(5,1) = ("Age-standardised rate")
putpdf table methods_measure_guide(5,2) = ("How do rates compare after allowing for differences in age structure?")
putpdf table methods_measure_guide(5,3) = ("Comparing years, sexes or populations more fairly")
putpdf table methods_measure_guide(.,.), font("`font_body'", 7.6)
putpdf table methods_measure_guide(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_measure_guide(2/5,1), bold font("`font_title'", 7.6, "`bnr_teal'")

putpdf paragraph
putpdf text ("Counts and percentages"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A count reports the number of eligible event episodes or classified deaths. A percentage shows how a stated total is distributed across groups. For example, the percentage of registered events occurring before age 70 describes the age pattern among those events; it represents a share of the event total rather than a person's chance of developing CVD."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Why denominators matter"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The denominator defines the population or total to which a result refers. Counts have no population denominator. Percentages use the eligible total named with the result. Population rates pair events or deaths with the resident population for the same year and, where relevant, the same sex and age group."), font("`font_body'", 8.4)


** NEW METHODS PAGE. Population rates and fair comparisons
putpdf pagebreak
putpdf paragraph
putpdf text ("Population rates and fair comparisons"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Why use a population rate?"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A count describes volume. A population rate relates that count to the number of residents who could contribute to it, allowing years or groups of different sizes to be compared. Event and mortality rates in this report are presented per 100,000 residents."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Crude and age-standardised rates"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_rate_guide = (3,3), width(100%) border(all, nil)
putpdf table methods_rate_guide(1,1) = ("Rate")
putpdf table methods_rate_guide(1,2) = ("What it describes")
putpdf table methods_rate_guide(1,3) = ("How to use it")
putpdf table methods_rate_guide(2,1) = ("Crude")
putpdf table methods_rate_guide(2,2) = ("The observed number of events or deaths in relation to the matching resident population")
putpdf table methods_rate_guide(2,3) = ("Describes the population's actual experience during that year")
putpdf table methods_rate_guide(3,1) = ("Age-standardised")
putpdf table methods_rate_guide(3,2) = ("The rate after applying the same standard age distribution to every year or group")
putpdf table methods_rate_guide(3,3) = ("Supports fairer comparison where population age structures differ")
putpdf table methods_rate_guide(.,.), font("`font_body'", 7.6)
putpdf table methods_rate_guide(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_rate_guide(2/3,1), bold font("`font_title'", 7.6, "`bnr_teal'")

putpdf paragraph
putpdf text ("Matching the population to the result"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Every event or death numerator is paired with the Barbados resident population for the same year. Rates for women and men use the corresponding sex-specific population. Age-specific rates use the population in the stated age group. The report uses United Nations World Population Prospects, 2024 edition, for the population estimates."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Age standardisation"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Cardiovascular disease is strongly related to age, and the age structure of a population can change over time. Direct age standardisation applies the WHO World Standard Population 2000-2025 to every comparison. This gives each year or group the same reference age structure, allowing differences in rates to be interpreted more fairly."), font("`font_body'", 8.4)

putpdf table methods_measure_note = (1,1), width(100%) border(all, nil)
putpdf table methods_measure_note(1,1) = ("TECHNICAL DETAIL | Full formulas, denominator specifications and standard-population information are provided in the online BNR Methods manual: `methods_url_public'"), ///
    font("`font_title'", 8.0, "`bnr_red_text'") bgcolor("`bnr_pale2'")
putpdf table methods_measure_note(1,1), border(top, single, "`bnr_red_text'")




** NEW METHODS PAGE. Understanding uncertainty and time
putpdf pagebreak 
putpdf paragraph
putpdf text ("Understanding uncertainty and time"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("Every surveillance estimate contains some uncertainty. In this report, uncertainty can arise when a rate is calculated from observed numbers, when hospital and death records are linked, and when the cardiovascular evidence on a death certificate is classified. We show each separately because each answers a different question about the result."), font("`font_body'", 8.4)

putpdf table methods_uncertainty = (4,3), width(100%) border(all, nil)
putpdf table methods_uncertainty(1,1) = ("Source of uncertainty")
putpdf table methods_uncertainty(1,2) = ("The question it answers")
putpdf table methods_uncertainty(1,3) = ("How it appears")
putpdf table methods_uncertainty(2,1) = ("Statistical precision")
putpdf table methods_uncertainty(2,2) = ("How precisely has the rate been estimated from the observed number of events or deaths?")
putpdf table methods_uncertainty(2,3) = ("95% confidence interval")
putpdf table methods_uncertainty(3,1) = ("Linkage uncertainty")
putpdf table methods_uncertainty(3,2) = ("How much could unresolved matching change the annual national event estimate?")
putpdf table methods_uncertainty(3,3) = ("Lower, central and upper linkage values")
putpdf table methods_uncertainty(4,1) = ("Classification sensitivity")
putpdf table methods_uncertainty(4,2) = ("How much does the mortality result change when Possible cardiovascular deaths are included?")
putpdf table methods_uncertainty(4,3) = ("Primary and Inclusive results")
putpdf table methods_uncertainty(.,.), font("`font_body'", 7.3)
putpdf table methods_uncertainty(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_uncertainty(2/4,1), bold font("`font_title'", 7.3, "`bnr_teal'")

putpdf paragraph
putpdf text ("How to read the three forms"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A narrower confidence interval indicates a more precise rate estimate. A wider linkage range shows that unresolved matching has more influence on the national event estimate. A larger difference between Primary and Inclusive mortality shows greater sensitivity to the classification of less-certain death-certificate evidence."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Statistical confidence intervals"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The 95% confidence interval shows the statistical precision of a published rate. Wider intervals commonly occur when the underlying number of events or deaths is small. Crude-rate intervals use the exact Poisson (Garwood) method where specified, and directly age-standardised rates use the Fay-Feuer gamma method."), font("`font_body'", 8.2)

putpdf paragraph
putpdf text ("Comparisons over time"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The previous-five-year mean is the average for the five complete calendar years immediately before the year being reported. It provides recent historical context for the current result. Longer-term charts show the full internally comparable series and help readers see whether a recent change forms part of a sustained pattern."), font("`font_body'", 8.4)

putpdf table methods_uncertainty_note = (1,1), width(100%) border(all, nil)
putpdf table methods_uncertainty_note(1,1) = ("WHEN READING THE REPORT | Read each form of uncertainty beside the estimate it describes. Together they show statistical precision, the influence of unresolved linkage and sensitivity to mortality classification."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_uncertainty_note(1,1), border(top, single, "`bnr_teal'")




** NEW METHODS PAGE. Data quality, confidentiality and publication
putpdf pagebreak
putpdf paragraph
putpdf text ("Data quality and publication"), ///
    bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Data quality metrics in Chapter 3"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("The Chapter 3 indicators show how two important parts of the method contribute to the published results: extending hospital-recorded events with eligible death records, and including Possible cardiovascular deaths in the broader mortality definition. They make the influence of these choices visible alongside the disease estimates."), font("`font_body'", 8.2)

putpdf table methods_quality_eq = (2,2), width(100%) border(all, nil)

putpdf table methods_quality_eq(1,1) = ("DCO contribution")
putpdf table methods_quality_eq(1,2) = ///
    ("The percentage of the Primary national event estimate contributed by eligible death-certificate-only events.")

putpdf table methods_quality_eq(2,1) = ("Possible-death reliance")
putpdf table methods_quality_eq(2,2) = ///
    ("The percentage of the Inclusive mortality total contributed by deaths in the Possible evidence class.")

putpdf table methods_quality_eq(.,.), font("`font_body'", 7.7)
putpdf table methods_quality_eq(.,1), ///
    bold font("`font_title'", 7.7, "`bnr_teal'")
putpdf table methods_quality_eq(1,.), ///
    border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Completeness"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("Where completeness is reported, it shows the proportion of eligible records containing the information required for that measure. Information that does not apply to a record is excluded from the expected total. Reading completeness alongside the results helps distinguish changes in recording from changes in CVD burden."), ///
    font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Protecting confidentiality"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("The BNR publishes aggregate totals, rates and summaries. Exact counts from 1 to 5 are suppressed, and additional values are protected where totals, calculated results or comparisons across releases could reveal a small count. An asterisk marks a protected result and means that its value remains confidential. Every proposed public release receives human review before approval."), ///
    font("`font_body'", 8.1)

putpdf table methods_disclosure_note = (1,1), width(100%) border(all, nil)
putpdf table methods_disclosure_note(1,1) = ("TECHNICAL DETAIL | The complete disclosure-control method is documented in the online BNR Methods manual: `methods_url_public'"), ///
    font("`font_title'", 8.0, "`bnr_red_text'") bgcolor("`bnr_pale2'")
putpdf table methods_disclosure_note(1,1), border(top, single, "`bnr_red_text'")

putpdf paragraph
putpdf text ("Before publication"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("The underlying data are prepared, checked, reviewed and approved before publication. The annual report then reads the named approved releases, preserving a traceable connection between the published data and every result shown here."), ///
    font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Responsible interpretation"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("Changes may reflect population health, access to care, diagnosis, recording, completeness, population estimates or several influences together. Strong interpretation compares like with like, distinguishes events from people and hospital-recorded results from national estimates, and reads each form of uncertainty beside the result it describes. Surveillance patterns provide evidence for decisions and help identify the questions that warrant further investigation."), ///
    font("`font_body'", 8.1)

putpdf table methods_final_note = (2,1), width(100%) border(all, nil)

putpdf table methods_final_note(1,1) = ///
    ("WHY THE RESULTS CAN BE TRUSTED"), ///
    bold font("`font_title'", 8.3, "`bnr_teal'")
putpdf table methods_final_note(2,1) = ///
    ("Consistent definitions, complementary data sources, explicit uncertainty, named public releases, confidentiality protection and human approval work together to produce results that are reliable, transparent, timely and safe to publish."), ///
    font("`font_body'", 8.3, "`bnr_teal'")

putpdf table methods_final_note(1,1), ///
    border(top, single, "`bnr_teal'")
putpdf table methods_final_note(2,1), ///
    border(bottom, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Further information"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("TEMPORARY WEB ADDRESSES - VERIFY BEFORE PUBLICATION"), ///
    bold font("`font_title'", 7.8, "`bnr_red_text'")
putpdf paragraph
putpdf text ("Public Methods manual: `methods_url_public'"), font("`font_body'", 7.8, "`bnr_red_text'")
putpdf paragraph
putpdf text ("Operations manual: `methods_url_operations'   Technical manual: `methods_url_technical'"), font("`font_body'", 7.8, "`bnr_red_text'")
