/*******************************************************************************
DO-FILE: bnr_report_annual_standard.do
VERSION: 2.5.1 (6 September 2026)
PURPOSE: Reusable putpdf composition for the standard annual CVD surveillance
         section.

CALLER:
  bnr_report_annual_s1_build.do only.

SOURCE BOUNDARY:
  This file reads only the two declared approved public release CSVs selected
  and checksum-validated by Step 1. It never reads confidential source data and
  it does not recalculate published surveillance rates.

DESIGN CONTRACT:
  - A4 portrait annual-report publication, not a printed dashboard.
  - Montserrat Medium is used for titling and Montserrat for body copy.
  - The UWI crest, restrained BNR palette and briefing-style white space provide
    the visual identity.
  - The cover and Year in Brief use fixed invisible-table layout grids so the
    page is composed deliberately rather than allowed to flow unpredictably.
  - Results graphics show the complete approved annual time series.
  - Exact result tables show the latest five complete years in wide form.
  - Public-facing headings use counts/events/deaths rather than "burden".
  - Graph furniture is deliberately sparse.
  - DCO/linkage uncertainty is shown as a pale band; published statistical
    confidence intervals are shown as whiskers.
  - Published five-year count comparators are used where they exist.
  - Interpretation remains analyst-owned in the year-specific interpretation
    file; this composition file does not generate editorial conclusions.
  - Special chapter composition remains outside this file.

DESIGN PASS 2.5.1:
  - Reserve one explicit front-matter page for the dynamic contents generated
    by the controlled PDF-finishing helper.
  - The placeholder is presentation metadata only. It contains no analytical
    information and must remain unique within the report body.

DESIGN PASS 2.2.0:
  - Keep summary-card backgrounds continuous behind labels and values.
  - Simplify interpretation callouts to one continuous pale panel.
  - Widen annual graphics, move legends to 12 o'clock, remove axis lines and
    add same-colour observed-value markers to line charts.
  - Increase use of published uncertainty without combining distinct sources:
    DCO linkage ranges are shaded; statistical 95% confidence intervals use
    whiskers.
  - Add a concise quarterly hospital-recorded "How the year unfolded" view.
  - Rebuild completeness graphics as labelled five-year tile matrices.
  - Expand Methods into a publication-grade technical section covering
    ascertainment, definitions, equations, uncertainty, disclosure and release
    governance.
  - Keep analytical definitions, release selection and workflow boundaries
    unchanged.

DESIGN PASS 2.4.0:
  - Rebuild the year-in-brief page as headline cards, one monthly event chart
    and three findings; remove the uninformative mini-trends and the separate
    quarterly page.
  - Round the four headline values and published confidence intervals to whole
    numbers for this high-level page.
  - Use explicit card spacer cells and white card surfaces with coloured top
    rules, avoiding putpdf's opaque text-background artefact.
  - Keep the disease-specific CVD, Heart and Stroke chapter expansion for the
    next design stage.

DESIGN PASS 2.5.0:
  - Replace combined subtype pages with a consistent All-CVD, Heart and Stroke
    sequence for counts, rates, women and men, and broad age patterns.
  - Apply the same disease-specific sequence to mortality, preserving Primary
    and Inclusive mortality definitions.
  - Keep all metric selection in an included, readable Stata section so the
    established annual workflow and publication boundary are unchanged.

DESIGN PASS 2.3.0:
  - Establish a single report type scale and a white-card, coloured-rule visual
    treatment that avoids opaque text-background artefacts in putpdf output.
  - Standardise metric strips, interpretation callouts and data-table headers
    around rules and whitespace rather than broad cell shading.
  - Page furniture is applied later by the Step 1 controlled PDF helper; it is
    deliberately outside this composition file and has no analytical role.
*******************************************************************************/

*******************************************************************************
* BNR ANALYST GUIDE - REUSABLE STANDARD SECTION
*
* BNR ANALYST: DO NOT EDIT THIS FILE for routine annual production.
* This is the invariant composition layer shared across reporting years. It
* selects already-published rows, draws the standard graphics and tables, and
* inserts analyst-owned narrative locals at predetermined positions. It must
* never read confidential data or become a second metric-calculation workflow.
*
* Safe annual narrative editing belongs in the year-specific interpretation
* DO file. A structural or graphical change here is a maintained template
* change: review it, build a new candidate version and inspect the whole PDF.
*
* IMPORTANT: the large `if 0 { ... }` block is disabled legacy reference code.
* Do not reactivate, edit, extract or reorder it during routine work.
*******************************************************************************

version 19.0

* -----------------------------------------------------------------------------
* 1. Required context and visual language
* -----------------------------------------------------------------------------
* INVARIANT TEMPLATE SETUP - DO NOT EDIT ROUTINELY.
* Confirm the user supplied a report year and two release IDs, require the
* crest, define the single palette/type scale, and create the private figures
* directory. These locals are reused by the standard and Special chapters.

if "`report_year4'" == "" {
    display as error "Annual standard composition requires local report_year4."
    exit 198
}
if "`event_release'" == "" | "`mortality_release'" == "" {
    display as error "Annual standard composition requires declared public release IDs."
    exit 198
}

local uwi_crest "$BNR_REPO/site/assets/images/uwi-crestonly-20p.png"
capture confirm file "`uwi_crest'"
if _rc {
    display as error "Required UWI crest not found: `uwi_crest'"
    exit 601
}

* RGB strings are retained as locals so the 2025 Special chapter can reuse them.
local bnr_ink       "44 62 80"
local bnr_teal      "4 81 116"
local bnr_primary   "43 115 136"
local bnr_secondary "91 139 151"
local bnr_women     "122 85 134"
local bnr_men       "45 103 141"
local bnr_stroke    "47 126 96"
local bnr_heart     "178 95 82"
local bnr_under70   "216 156 96"
local bnr_70plus    "122 135 148"
local bnr_pale      "240 246 248"
local bnr_pale2     "248 249 250"
local bnr_white     "255 255 255"
local bnr_rule      "222 226 230"
local bnr_muted     "102 102 102"
local bnr_green     "214 237 223"
local bnr_amber     "255 231 168"
local bnr_red       "243 198 204"
local bnr_green_text "0 128 70"
local bnr_amber_text "181 103 0"
local bnr_red_text   "190 0 32"

* Base CVD colour: 4 81 116
local bnr_women_all_cvd "4 116 161"     // lighter
local bnr_men_all_cvd   "4 46 71"       // darker

* Base Heart colour: 178 95 82
local bnr_women_heart "233 130 112" // lighter
local bnr_men_heart   "123 60 52"   // darker

* Base Stroke colour: 47 126 96
local bnr_women_stroke "72 171 131" // lighter
local bnr_men_stroke   "22 81 61"   // darker

* Publication typography. These fonts are part of the intended analytics
* environment. A separate report style sheet will be produced once the visual
* system has stabilised.
local font_title      "Montserrat Medium"
local font_body       "Montserrat"
local font_body_med   "Montserrat Medium"
local font_body_light "Montserrat Light"

* One reusable A4 type scale. Page-specific design may use these local names,
* but must not introduce a second heading hierarchy.
local size_chapter  18
local size_page     14
local size_section  11
local size_deck      8
local size_body      8.4
local size_table     7.8
local size_label     7.5
local size_value    14

local first_table_year = `report_year_num' - 4

capture mkdir "`candidate_dir'/figures"
local annual_figure_dir "`candidate_dir'/figures"

* -----------------------------------------------------------------------------
* 2. Read the two approved public releases once
* -----------------------------------------------------------------------------
* INVARIANT PUBLIC-DATA BOUNDARY - DO NOT EDIT.
* Import the two Step 1 checksum-validated public CSVs, convert only published
* numeric columns and cache them as temporary Stata datasets. No confidential
* source, linkage record or private analytical input may be introduced here.

tempfile annual_event_data annual_mortality_data

import delimited using "`event_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_month period_quarter period_complete value numerator denominator ///
        linkage_lower_value linkage_upper_value ci_lower_value ci_upper_value ///
        comparison_n {
    capture destring `v', replace force
}
save "`annual_event_data'", replace

import delimited using "`mortality_csv'", clear varnames(1) stringcols(_all)
foreach v in period_year period_complete value numerator denominator ///
        ci_lower_value ci_upper_value comparison_n {
    capture destring `v', replace force
}
save "`annual_mortality_data'", replace

* -----------------------------------------------------------------------------
* 3. Latest-year values used on cover-summary cards
* -----------------------------------------------------------------------------
* INVARIANT METRIC SELECTION - DO NOT EDIT ROUTINELY.
* Select the four headline results and their released confidence limits. This
* block formats existing public values; it does not calculate surveillance
* rates. Changes to metric IDs, scopes, definitions or strata require formal
* template review because they alter the meaning of the summary page.

local yib_event_count "Not available"
local yib_event_rate "Not available"
local yib_event_rate_ci ""
local yib_death_count "Not available"
local yib_death_rate "Not available"
local yib_death_rate_ci ""

use "`annual_event_data'", clear
preserve
    keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_event_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "CVD-INCIDENCE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        ascertainment_scope == "hospital_plus_dco" & ///
        mortality_definition == "primary" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_event_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_event_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore
use "`annual_mortality_data'", clear
preserve
    keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "all" & ///
        case_definition == "primary_clear_likely" & statistic == "annual_count"
    quietly count
    if r(N) == 1 {
        local tmp : display %9.0fc value[1]
        local yib_death_count = strtrim("`tmp'")
    }
restore
preserve
    keep if metric_id == "MORT-RATE-001" & period_type == "annual" & ///
        period_year == `report_year_num' & event_type == "all_cvd" & ///
        sex == "all" & age_group == "age_standardised" & ///
        case_definition == "primary_clear_likely" & ///
        statistic == "annual_age_standardised_rate"
    quietly count
    if r(N) == 1 {
        local tmp : display %6.0f value[1]
        local yib_death_rate = strtrim("`tmp'")
        if !missing(ci_lower_value[1], ci_upper_value[1]) {
            local lo : display %6.0f ci_lower_value[1]
            local hi : display %6.0f ci_upper_value[1]
            local yib_death_rate_ci = "95% CI " + strtrim("`lo'") + "-" + strtrim("`hi'")
        }
    }
restore



* -----------------------------------------------------------------------------
* 4. Plain cover
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION BLOCK - NOT A ROUTINE ANALYST EDIT.
* Compose the cover within one fixed invisible table so pagination is stable.
* Text or branding changes should be treated as report-template changes and
* checked against the finished, furniture-stamped PDF.

* The cover is held in one invisible layout grid. This avoids the page-flow
* behaviour of the first prototype, where each cover element could land on a
* separate page.

putpdf table cover = (5,1), width(15%) border(all, nil) halign(center)
putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = (" ")
putpdf table cover(4,1) = (" ")
putpdf table cover(5,1) = image("`uwi_crest'"), halign(center)

putpdf table cover = (8,12), width(88%) border(all, nil) halign(center)
putpdf table cover(1,1), colspan(12)
putpdf table cover(2,1), colspan(12)
putpdf table cover(3,1), colspan(12)
putpdf table cover(4,1), colspan(12)
putpdf table cover(5,1), colspan(12)
putpdf table cover(6,1), colspan(12)
putpdf table cover(7,1), colspan(12)
putpdf table cover(8,1), colspan(12)

putpdf table cover(1,1) = (" ")
putpdf table cover(2,1) = (" ")
putpdf table cover(3,1) = ("BARBADOS NATIONAL REGISTRY"), ///
    halign(center) font("`font_title'", 10, "`bnr_teal'")
putpdf table cover(4,1) = ("Annual cardiovascular disease report"), ///
    halign(center) bold font("`font_title'", 24, "`bnr_ink'")
putpdf table cover(5,1) = ("`report_year4'"), ///
    halign(center) bold font("`font_title'", 30, "`bnr_ink'")
putpdf table cover(6,1) = ("Cardiovascular disease events and mortality in Barbados"), ///
    halign(center) font("`font_body'", 11, "`bnr_muted'")
putpdf table cover(7,1) = (" ")
putpdf table cover(8,1) = ("The University of the West Indies | Cave Hill Campus"), ///
    halign(center) font("`font_body'", 8, "`bnr_muted'")



* -----------------------------------------------------------------------------
* 5A. Report information and front matter
* -----------------------------------------------------------------------------
* MAINTAINED FRONT-MATTER BLOCK.
* This page is public report metadata and explanatory context. Update authors,
* affiliations, acknowledgements and contact details when the report ownership
* changes. Do not alter the release identifiers or analytical definitions here.
*
* The report year, event release and mortality release are supplied by the
* controlled annual build workflow.

putpdf pagebreak

putpdf paragraph, font("`font_body'", 1)
putpdf text ("About this report"), ///
    bold font("`font_title'", 19, "`bnr_ink'") linebreak

putpdf text ("Annual cardiovascular disease report `report_year4'"), ///
    bold font("`font_title'", 11, "`bnr_teal'") linebreak

putpdf text ("Cardiovascular disease events and mortality in Barbados"), ///
    font("`font_body'", 9, "`bnr_muted'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Purpose and scope"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("This report provides an annual overview of cardiovascular disease events and mortality in Barbados. It presents results on the burden of heart attacks and strokes in Barbados, together with selected sex and age summaries. The report is publically available, and is particularly aimed at supporting decision-making by government, hospitals, clinics, public-health teams, researchers and other partners."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 2)

putpdf text ///
    ("The report presents a range of annual aggregated observations using the quality-controlled and approved BNR data releases. Estimates should be interpreted alongside the definitions, coverage notes and uncertainty information provided in the report. The report and the underlying data are available from the BNR Information Hub."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Report information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf table report_frontmatter = (6,2), width(100%) border(all, nil)

putpdf table report_frontmatter(1,1) = ("Report")
putpdf table report_frontmatter(1,2) = ///
    ("Annual cardiovascular disease report `report_year4'")

putpdf table report_frontmatter(2,1) = ("Prepared by")
putpdf table report_frontmatter(2,2) = ///
    ("Christina Howitt; Jacqueline Campbell; Ian Hambleton")

putpdf table report_frontmatter(3,1) = ("Institution")
putpdf table report_frontmatter(3,2) = ///
    ("Barbados National Registry | The University of the West Indies, Cave Hill Campus")

putpdf table report_frontmatter(4,1) = ("Approved data releases")
putpdf table report_frontmatter(4,2) = ///
    ("CVD events: `event_release' | CVD mortality: `mortality_release'")

putpdf table report_frontmatter(5,1) = ("Online report")
putpdf table report_frontmatter(5,2) = ///
    ("https://uwi-bnr.github.io/info-hub/")

putpdf table report_frontmatter(6,1) = ("Suggested citation")

putpdf table report_frontmatter(6,2) = ///
    ("Howitt C, Campbell J, Hambleton I for the Barbados National Registry. ")

putpdf table report_frontmatter(6,2) = ///
    ("Annual cardiovascular disease report `report_year4': cardiovascular disease events and mortality in Barbados. "), italic append

putpdf table report_frontmatter(6,2) = ///
    ("The University of the West Indies, Cave Hill Campus, Bridgetown, Barbados."), append

putpdf table report_frontmatter(.,.), ///
    font("`font_body'", 7.8, "`bnr_ink'") ///
    bgcolor("`bnr_white'")

putpdf table report_frontmatter(1,.), ///
    bold font("`font_title'", 7.8, "`bnr_teal'") ///
    border(top, single, "`bnr_teal'") ///
    border(bottom, single, "`bnr_rule'")

putpdf table report_frontmatter(2/6,1), ///
    bold font("`font_title'", 7.8, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Acknowledgements"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("The Barbados National Registry acknowledges the clinical, hospital, registry, data-management and public-health teams whose work supports the production of this surveillance report."), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ("Further information"), ///
    bold font("`font_title'", 11, "`bnr_ink'") linebreak

putpdf text ///
    ("Definitions, ascertainment rules, mortality classifications, uncertainty measures, data availability and disclosure controls are described in the BNR Methods manual, available online. These methods, latest public report and associated data products are available at: https://uwi-bnr.github.io/info-hub/"), ///
    font("`font_body'", 8.5, "`bnr_ink'")

putpdf paragraph, font("`font_body'", 3)

putpdf text ///
    ("Publication note: This edition is produced through the controlled BNR annual-report build, approval and publication workflow. The public version is the approved version deposited through that workflow."), ///
    italic font("`font_body'", 7.4, "`bnr_muted'")

* -----------------------------------------------------------------------------
* 5B. Dynamic contents placeholder
* -----------------------------------------------------------------------------
* INVARIANT PRESENTATION HAND-OFF - DO NOT EDIT OR DUPLICATE.
* Stata owns the position of the Contents page. The controlled Python finishing
* helper replaces this complete page after it has identified the sections that
* actually exist in the rendered body PDF. The unique marker is deliberately
* unobtrusive because the unstamped body PDF remains private.

putpdf pagebreak
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Contents"), bold font("`font_title'", 19, "`bnr_ink'") linebreak
putpdf text ("BNR_TOC_PLACEHOLDER"), font("`font_body'", 1, "`bnr_white'")

* -----------------------------------------------------------------------------
* 5C. Year in brief - one-page visual summary
* -----------------------------------------------------------------------------
* MAINTAINED PRESENTATION AND METRIC-SELECTION BLOCK.
* BNR ANALYST: do not change filters or calculations here. This block draws the
* approved monthly hospital-recorded series, lays out four headline cards and
* inserts three editable messages defined in the year interpretation file.

* Month-on-month CVD events.
* All years other than the report year are faded lines without dots.
* The current report year is overlaid as the prominent connected line.
* This automatically updates for future annual reports.

local yib_monthly_fig "`annual_figure_dir'/yib_monthly_events.png"
use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & ///
    period_type == "monthly" & ///
    event_type == "all_cvd" & ///
    sex == "all" & ///
    age_group == "all" & ///
    ascertainment_scope == "hospital_only" & ///
    statistic == "monthly_count" & ///
    period_complete == 1
quietly count

if r(N) >= 2 {
    sort period_year period_month

    * Create one variable for each historical year.
    * The current report year is excluded from these variables.
    separate value if period_year != `report_year_num', ///
        by(period_year) generate(yib_historical)

    * Create rolling comparator years 
    unab yib_historical_vars : yib_historical*
    local yib_historical_colours
    foreach v of local yib_historical_vars {
        local yib_historical_colours `"`yib_historical_colours' "`bnr_teal'%20""'
    }

    #delimit ; 
    twoway 
        (line yib_historical* period_month, sort lcolor(`yib_historical_colours') lwidth(thin)) 
        (connected value period_month if period_year == `report_year_num', sort 
            lcolor("`bnr_teal'") mcolor("`bnr_teal'") msymbol(O) msize(5) 
            lwidth(1))
            , 
		plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
		graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))
        xlabel(1 "Jan" 2 " " 3 " " 4 "Apr" 5 " " 6 " " 
               7 "Jul" 8 " " 9 " " 10 "Oct" 11 " " 12 " ",
               labsize(9) noticks nogrid)
        ylabel(#4, angle(horizontal) labsize(9) noticks nogrid) 
        xscale(noline range(0.5(1)12.5)) yscale(noline range(70(5)110)) 
        xtitle("") ytitle("", size(vsmall)) legend(off) 
        xsize(7.6) ysize(1.55)
        name(yib);
    #delimit cr 
    graph export "`yib_monthly_fig'", replace width(2600)
}

putpdf pagebreak
putpdf paragraph, font("`font_body'", 1)
putpdf text ("`report_year4' in brief"), bold font("`font_title'", 20, "`bnr_ink'") linebreak
putpdf text ("The latest complete year at a glance"), ///
    font("`font_body'", 9, "`bnr_muted'")

* Four explicit cards. Column 2 and row 4 are intentional spacer cells. White
* card surfaces eliminate putpdf's visible opaque text-background artefact.
putpdf table yib_cards = (7,3), width(100%) border(all, nil)
forvalues r = 1/7 {
    putpdf table yib_cards(`r',2) = ("")
}
putpdf table yib_cards(4,1) = (""), font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(4,3) = (""), font("`font_title'", 2.5, "`bnr_teal'")

putpdf table yib_cards(1,1) = ("CVD EVENTS"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,1) = ("`yib_event_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,1) = ("Primary national estimate"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(1,3) = ("CVD EVENT RATE"), bold font("`font_title'", 7.5, "`bnr_teal'")
putpdf table yib_cards(2,3) = ("`yib_event_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(3,3) = ("Age-standardised | `yib_event_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,1) = ("CVD DEATHS"), bold font("`font_title'", 7.5, "`bnr_heart'")
putpdf table yib_cards(6,1) = ("`yib_death_count'"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,1) = ("Primary definition"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(5,3) = ("CVD MORTALITY RATE"), bold font("`font_title'", 7.5, "`bnr_secondary'")
putpdf table yib_cards(6,3) = ("`yib_death_rate' per 100,000"), bold font("`font_title'", 17, "`bnr_ink'")
putpdf table yib_cards(7,3) = ("Age-standardised | `yib_death_rate_ci'"), font("`font_body'", 7.3, "`bnr_muted'")
putpdf table yib_cards(.,.), bgcolor("`bnr_white'")
putpdf table yib_cards(1,1), border(top, single, "`bnr_teal'")
putpdf table yib_cards(1,3), border(top, single, "`bnr_teal'")
putpdf table yib_cards(5,1), border(top, single, "`bnr_heart'")
putpdf table yib_cards(5,3), border(top, single, "`bnr_secondary'")

putpdf paragraph, font("`font_body'", 1)
putpdf text ("How the year unfolded"), bold font("`font_title'", 10.5, "`bnr_ink'")
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Monthly hospital-recorded CVD events in `report_year4'. Unlike hospital events, national event estimates are updated annually because events captured only through death-record are added after each year closes."), font("`font_body'", 7.4, "`bnr_muted'")
capture confirm file "`yib_monthly_fig'"
if !_rc {
    putpdf table yib_monthly = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table yib_monthly(1,1) = image("`yib_monthly_fig'")
}

putpdf paragraph, font("`font_body'", 1)
putpdf text ("What stood out in `report_year4'?"), ///
    bold font("`font_title'", 10.5, "`bnr_ink'")

putpdf table yib_messages = (4,12), width(100%) border(all, nil)
forvalues rr = 1/4 {
    putpdf table yib_messages(`rr',1)
    putpdf table yib_messages(`rr',2), colspan(11)
    putpdf table yib_messages(`rr',1) = ("0`rr'"), ///
        halign(center) bold font("`font_title'", 9, "`bnr_teal'")
}
putpdf table yib_messages(1,2) = ("`annual_summary_message_1'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(2,2) = ("`annual_summary_message_2'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(3,2) = ("`annual_summary_message_3'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")
putpdf table yib_messages(4,2) = ("`annual_summary_message_4'"), ///
    font("`font_body'", 7.5, "`bnr_ink'")




* -----------------------------------------------------------------------------
* 6. Stage 3 disease-specific event and mortality sections
* -----------------------------------------------------------------------------

* INVARIANT INCLUDE POINT - DO NOT MOVE.
* The included template creates all live Chapter 1 and Chapter 2 pages in this
* position. Its internal comments identify each graphic, table and narrative
* hook. Moving the include changes report order and page flow.

include "$BNR_REPO/scripts/stata/reporting/templates/bnr_report_annual_stage3_sections.do"



* -----------------------------------------------------------------------------
* 16. How complete is the picture? - E1/E2 quality matrices
* -----------------------------------------------------------------------------

* CHAPTER 3 - MAINTAINED QUALITY PRESENTATION.
* BNR ANALYST: the graphics may be refined only as an approved template change.
* Do not change the public metrics or definitions. The first matrix describes
* the published DCO contribution to Primary national event estimates; the
* second describes reliance on Possible deaths within Inclusive mortality.
* Percentages are presentation summaries of released aggregate counts.

local fig_e1 "`annual_figure_dir'/quality_event_dco.png"
local fig_e2 "`annual_figure_dir'/quality_possible_deaths.png"
local quality_first_year = `report_year_num' - 14

use "`annual_event_data'", clear
keep if metric_id == "CVD-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    ((ascertainment_scope == "additional_dco" & mortality_definition == "primary") | ///
     (ascertainment_scope == "hospital_plus_dco" & mortality_definition == "primary"))
keep period_year event_type ascertainment_scope value
reshape wide value, i(period_year event_type) j(ascertainment_scope) string
gen double quality_pct = 100 * valueadditional_dco / valuehospital_plus_dco
gen byte quality_band = cond(quality_pct < 10, 1, cond(quality_pct < 15, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)

local x_range_min = `quality_first_year' - 1 
local x_range_max = `report_year_num' + 1

if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_mort)
      ;
    #delimit cr
    graph export "`fig_e1'", replace width(2800)
}

use "`annual_mortality_data'", clear
keep if metric_id == "MORT-BURDEN-001" & period_type == "annual" & ///
    inrange(period_year, `quality_first_year', `report_year_num') & period_complete == 1 & sex == "all" & ///
    age_group == "all" & statistic == "annual_count" & ///
    inlist(event_type, "all_cvd", "heart", "stroke") & ///
    inlist(case_definition, "primary_clear_likely", "upper_clear_likely_possible")
keep period_year event_type case_definition value
reshape wide value, i(period_year event_type) j(case_definition) string
gen double quality_pct = 100 * ///
    (valueupper_clear_likely_possible - valueprimary_clear_likely) / ///
    valueupper_clear_likely_possible
gen byte quality_band = cond(quality_pct < 20, 1, cond(quality_pct < 30, 2, 3))
gen byte y = cond(event_type == "all_cvd", 3, cond(event_type == "heart", 2, 1))
gen str8 tile_label = string(quality_pct, "%3.0f")
quietly count if !missing(quality_pct)
if r(N) > 0 {
    #delimit ;
    twoway 

      (scatter y period_year if quality_band == 1, msymbol(square) msize(18) mcolor("`bnr_green'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 2, msymbol(square) msize(18) mcolor("`bnr_amber'")
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'")) 

      (scatter y period_year if quality_band == 3, msymbol(square) msize(18) mcolor("`bnr_red'") 
          mlabel(tile_label) mlabposition(0) mlabsize(7) mlabcolor("`bnr_ink'"))
      , 

	  plotregion(c(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0)) 		
	  graphregion(color(gs16) ic(gs16) ilw(thin) lw(thin) margin(l=2 r=2 b=0 t=0))          

      xlabel(`quality_first_year'(2)`report_year_num', format(%4.0f) labsize(7) noticks nogrid) 

      ylabel(1 "Stroke" 2 "Heart" 3 "All CVD", angle(horizontal) labsize(7) labgap(2) noticks nogrid) 

      xscale(noline range(`x_range_min'(1)`x_range_max')) 
      yscale(noline range(0.5(1)3.5)) xtitle("") ytitle("") 

      legend(off)
      xsize(10.0) ysize(2.7)
      name(quality_dco)
      ;
    #delimit cr
    graph export "`fig_e2'", replace width(2800)
}

putpdf pagebreak
putpdf paragraph
putpdf text ("3 | How complete is the picture?"), bold font("`font_title'", `size_chapter', "`bnr_ink'")
putpdf paragraph
putpdf text ("Events identified through death records"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph

putpdf text ("Each tile gives the estimated additional DCO contribution as a percentage of the Primary national event estimate. The latest 15 complete years are shown. "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("Green "), bold font("`font_body'", 8, "`bnr_green_text'")
putpdf text ("is lower reliance, "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("amber "), font("`font_body'", 8, "`bnr_amber_text'")
putpdf text ("moderate "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("and "), font("`font_body'", 8, "`bnr_muted'")
putpdf text ("red "), font("`font_body'", 8, "`bnr_red_text'")
putpdf text ("higher."), font("`font_body'", 8, "`bnr_muted'")


capture confirm file "`fig_e1'"
if !_rc {
    putpdf table e1_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e1_fig(1,1) = image("`fig_e1'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e1_note = (2,1), width(100%) border(all, nil)
putpdf table e1_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e1_note(2,1) = ("`ann_evt_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e1_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Reliance on Possible deaths"), bold font("`font_title'", 13, "`bnr_ink'")
putpdf paragraph
putpdf text ("Possible-only deaths as a percentage of the Inclusive annual mortality count. Green is lower reliance, amber moderate and red higher; the percentage remains the main information."), font("`font_body'", 8, "`bnr_muted'")
capture confirm file "`fig_e2'"
if !_rc {
    putpdf table e2_fig = (1,1), width(100%) border(all, nil) halign(center)
    putpdf table e2_fig(1,1) = image("`fig_e2'")
}
putpdf paragraph, font("`font_body'", 1)
putpdf table e2_note = (2,1), width(100%) border(all, nil)
putpdf table e2_note(1,1) = ("WHAT THIS MEANS"), ///
    bold font("`font_title'", 8.5, "`bnr_teal'")
putpdf table e2_note(2,1) = ("`ann_mort_quality_text'"), ///
    font("`font_body'", 8.1, "`bnr_ink'")
putpdf table e2_note(.,.), bgcolor("`bnr_white'") border(top, single, "`bnr_teal'")


* -----------------------------------------------------------------------------
* 19. Methods - what we did and what the numbers mean
* -----------------------------------------------------------------------------

* METHODS CHAPTER - CONTROLLED STANDARD TEXT.
* BNR ANALYST: do not casually edit definitions, equations or governance text.
* This section explains the established public workflow; it does not execute
* the underlying event, mortality, rate, suppression or approval methods.
* Material amendments require methods and governance review, not annual copy
* editing alone.

putpdf pagebreak
putpdf paragraph
putpdf text ("4 | Methods"), bold font("`font_title'", `size_chapter', "`bnr_ink'")
putpdf paragraph
putpdf text ("What this report measures"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("`annual_methods_note'"), font("`font_body'", 8.5)

putpdf paragraph
putpdf text ("Data used for this report"), bold font("`font_title'", 14, "`bnr_ink'")

local event_first "-"
local event_last "-"
local mort_first "-"
local mort_last "-"
use "`annual_event_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "CVD-BURDEN-001", meanonly
if r(N) > 0 {
    local event_first = string(r(min), "%4.0f")
    local event_last = string(r(max), "%4.0f")
}
use "`annual_mortality_data'", clear
quietly summarize period_year if period_type == "annual" & period_complete == 1 & metric_id == "MORT-BURDEN-001", meanonly
if r(N) > 0 {
    local mort_first = string(r(min), "%4.0f")
    local mort_last = string(r(max), "%4.0f")
}
putpdf table availability = (3,4), width(100%) border(all, nil)
putpdf table availability(1,1) = ("Series")
putpdf table availability(1,2) = ("First complete annual year")
putpdf table availability(1,3) = ("Latest complete annual year")
putpdf table availability(1,4) = ("Data release used")
putpdf table availability(2,1) = ("CVD events")
putpdf table availability(2,2) = ("`event_first'")
putpdf table availability(2,3) = ("`event_last'")
putpdf table availability(2,4) = ("`event_release'")
putpdf table availability(3,1) = ("CVD mortality")
putpdf table availability(3,2) = ("`mort_first'")
putpdf table availability(3,3) = ("`mort_last'")
putpdf table availability(3,4) = ("`mortality_release'")
putpdf table availability(.,.), font("`font_body'", 8)
putpdf table availability(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table availability(.,1), bold

putpdf paragraph
putpdf text ("Population, period and unit of analysis"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("This report describes eligible cardiovascular events and deaths among Barbados residents. Event statistics report events rather than necessarily unique people: one person may contribute more than one eligible event. This annual report uses complete annual periods - always Jan to Dec - from the two declared public data releases. All data summaries presented are annual. The one exception is the monthly "), font("`font_body'", 8.4)
putpdf text ("How the year unfolded "), italic font("`font_body'", 8.4)
putpdf text ("chart in the section: `report_year4' in Brief."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Measures used in Chapters 1 to 3"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_metric_map = (8,4), width(100%) border(all, nil)
putpdf table methods_metric_map(1,1) = ("Report measure")
putpdf table methods_metric_map(1,2) = ("What is counted or compared")
putpdf table methods_metric_map(1,3) = ("Principal source")
putpdf table methods_metric_map(1,4) = ("Denominator")
putpdf table methods_metric_map(2,1) = ("Event counts")
putpdf table methods_metric_map(2,2) = ("Eligible CVD events")
putpdf table methods_metric_map(2,3) = ("Hospital records, with annual DCO-enhanced estimates")
putpdf table methods_metric_map(2,4) = ("None")
putpdf table methods_metric_map(3,1) = ("Event rates")
putpdf table methods_metric_map(3,2) = ("Eligible events relative to population")
putpdf table methods_metric_map(3,3) = ("Event release and approved population data")
putpdf table methods_metric_map(3,4) = ("Matching resident population")
putpdf table methods_metric_map(4,1) = ("Event patterns")
putpdf table methods_metric_map(4,2) = ("Events by sex or broad age group")
putpdf table methods_metric_map(4,3) = ("Event release")
putpdf table methods_metric_map(4,4) = ("Relevant eligible event group")
putpdf table methods_metric_map(5,1) = ("Death counts")
putpdf table methods_metric_map(5,2) = ("Deaths meeting a BNR mortality definition")
putpdf table methods_metric_map(5,3) = ("Death-certificate information")
putpdf table methods_metric_map(5,4) = ("None")
putpdf table methods_metric_map(6,1) = ("Mortality rates")
putpdf table methods_metric_map(6,2) = ("Classified deaths relative to population")
putpdf table methods_metric_map(6,3) = ("Mortality release and approved population data")
putpdf table methods_metric_map(6,4) = ("Matching resident population")
putpdf table methods_metric_map(7,1) = ("Mortality patterns")
putpdf table methods_metric_map(7,2) = ("Classified deaths by sex or broad age group")
putpdf table methods_metric_map(7,3) = ("Mortality release")
putpdf table methods_metric_map(7,4) = ("Relevant classified-death group")
putpdf table methods_metric_map(8,1) = ("Quality measures")
putpdf table methods_metric_map(8,2) = ("Reliance on additional or less-certain information")
putpdf table methods_metric_map(8,3) = ("Approved release aggregates")
putpdf table methods_metric_map(8,4) = ("Measure-specific eligible total")
putpdf table methods_metric_map(.,.), font("`font_body'", 7.3)
putpdf table methods_metric_map(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_metric_map(2/8,1), bold



** NEW METHODS PAGE. How CVD events are identified
putpdf pagebreak
putpdf paragraph
putpdf text ("How CVD events are identified"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("Consistent event rules allow changes over time to be interpreted more fairly. Records are included only after the approved disease, residence, date, source and duplicate-resolution rules have been applied. The time series presented in this report is internally comparable from 2010 onwards. However, changes in methodology introduced in 2025 mean that estimates in this report should not be compared directly with estimates published in reports from 2023 or earlier."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Heart, Stroke and All CVD"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Heart and Stroke are the two broad event families used in this report. All CVD combines eligible events or deaths from those families according to an approved classification hierarchy, so the same event or death is not counted twice merely because more than one cardiovascular term is present on clinical records or death certification."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Heart and Stroke event definitions"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("In the event series, Heart is the BNR reporting label for eligible acute myocardial infarction (heart-attack) events. Stroke is the BNR reporting label for eligible acute stroke events. We apply diagnostic, residence, date and duplicate-resolution rules before assigning an event to either family."), font("`font_body'", 8.4)

putpdf table methods_event_families = (3,2), width(100%) border(all, nil)
putpdf table methods_event_families(1,1) = ("Reporting family")
putpdf table methods_event_families(1,2) = ("What it represents")
putpdf table methods_event_families(2,1) = ("Heart")
putpdf table methods_event_families(2,2) = ///
    ("Acute myocardial infarction events among Barbados residents (ICD-10 I21–I22), confirmed under BNR clinical and validation rules.")
putpdf table methods_event_families(3,1) = ("Stroke")
putpdf table methods_event_families(3,2) = ///
    ("Stroke events among Barbados residents (ICD-10 I60–I64), confirmed under BNR clinical and validation rules.")
putpdf table methods_event_families(.,.), font("`font_body'", 7.5)
putpdf table methods_event_families(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_event_families(2/3,1), bold

putpdf table methods_event_rules = (7,2), width(100%) border(all, nil)
putpdf table methods_event_rules(1,1) = ("Decision")
putpdf table methods_event_rules(1,2) = ("How it affects the published statistic")
putpdf table methods_event_rules(2,1) = ("Disease definition")
putpdf table methods_event_rules(2,2) = ("The record must meet the approved Heart or Stroke criteria.")
putpdf table methods_event_rules(3,1) = ("Residence")
putpdf table methods_event_rules(3,2) = ("The event must relate to a person who was resident in Barbados for at least six months of the relevant calendar year.")
putpdf table methods_event_rules(4,1) = ("Event date")
putpdf table methods_event_rules(4,2) = ("The approved event date places the event in its reporting period.")
putpdf table methods_event_rules(5,1) = ("Duplicate resolution")
putpdf table methods_event_rules(5,2) = ("Records describing the same event episode are resolved before counting.")
putpdf table methods_event_rules(6,1) = ("Repeat event")
putpdf table methods_event_rules(6,2) = ("A later eligible event may be counted separately when it falls outside the approved 28-day event window.")
putpdf table methods_event_rules(7,1) = ("Analytical completeness")
putpdf table methods_event_rules(7,2) = ("A record must contain the information required for the selected measure.")
putpdf table methods_event_rules(.,.), font("`font_body'", 7.7)
putpdf table methods_event_rules(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_event_rules(2/7,1), bold

putpdf paragraph
putpdf text ("Events and people"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The unit of analysis is an event, not necessarily a unique person. Records within an event window (28-days) are considered a single event episode; a later event can contribute another count when it occurs at least 28-days after a recorded previous event. Event counts should therefore not be described as numbers of different people."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Hospital-recorded ascertainment"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Hospital-recorded statistics use eligible events identified from hospital information. The Queen Elizabeth Hospital is Barbados's only tertiary hospital, making this series an important view of serious recognised CVD events. It is not assumed to represent complete national ascertainment: access to care, referral, diagnosis and recording can all affect what is observed. For true national CVD estimates, we add death-certificate-only (DCO) events to the hospital events. The process for doing this is described in the next section."), font("`font_body'", 8.4)



** NEW METHODS PAGE. Extending the picture using death records
putpdf pagebreak
putpdf paragraph
putpdf text ("Extending the picture using death records"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("Some eligible cardiovascular events are identified only through death information. These death-certificate-only events broaden the annual picture beyond hospital records, but they introduce additional questions about classification and whether a death record matches an event already counted by the hospital."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("What is a DCO event?"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A death-certificate-only (DCO) event is an eligible event identified from death information without a matched eligible hospital-recorded event. DCO-enhanced event counts and rates are annual only. Monthly and quarterly event views remain hospital-recorded because death-record ascertainment closes at year-end."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("How linkage is undertaken"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_linkage = (5,2), width(100%) border(all, nil)
putpdf table methods_linkage(1,1) = ("Stage")
putpdf table methods_linkage(1,2) = ("Plain-language description")
putpdf table methods_linkage(2,1) = ("1  Prepare")
putpdf table methods_linkage(2,2) = ///
    ("We prepare the hospital records and relevant death records for secure comparison.")
putpdf table methods_linkage(3,1) = ("2  Match")
putpdf table methods_linkage(3,2) = ///
    ("We compare records using trusted combinations of names, dates and other identifying details, starting with the clearest matches.")
putpdf table methods_linkage(4,1) = ("3  Resolve")
putpdf table methods_linkage(4,2) = ///
    ("Clear matches are accepted. Records that do not match clearly are kept separate rather than being linked by guesswork.")
putpdf table methods_linkage(5,1) = ("4  Aggregate")
putpdf table methods_linkage(5,2) = ///
    ("We use the linked information to produce the event counts used in the report. Personal identifiers are removed before anything is published.")
putpdf table methods_linkage(.,.), font("`font_body'", 7.6)
putpdf table methods_linkage(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_linkage(2/5,1), bold font("`font_title'", 7.6, "`bnr_teal'")

putpdf paragraph
putpdf text ("Published national representations"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table event_scope = (4,3), width(100%) border(all, nil)
putpdf table event_scope(1,1) = ("Published series")
putpdf table event_scope(1,2) = ("Source coverage")
putpdf table event_scope(1,3) = ("Interpretation")
putpdf table event_scope(2,1) = ("Hospital-recorded")
putpdf table event_scope(2,2) = ("Eligible hospital events")
putpdf table event_scope(2,3) = ("Observed serious events recorded through the hospital source")
putpdf table event_scope(3,1) = ("Primary national")
putpdf table event_scope(3,2) = ("Hospital events plus DCO contribution based on Clear + Likely mortality evidence")
putpdf table event_scope(3,3) = ("Our primary annual estimate")
putpdf table event_scope(4,1) = ("Inclusive national")
putpdf table event_scope(4,2) = ("Hospital events plus DCO contribution that also includes Possible mortality evidence")
putpdf table event_scope(4,3) = ("A broader national estimate using the wider case definition, which is more sensitive to differences in how cases are classified.")
putpdf table event_scope(.,.), font("`font_body'", 7.4)
putpdf table event_scope(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table event_scope(2/4,1), bold

putpdf paragraph
putpdf text ("Linkage uncertainty range"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Where records cannot be linked with certainty and this could affect the national total, the public data provides three values. The lower value uses the more conservative interpretation, the central value is the main estimate reported by the BNR, and the upper value includes the wider contribution that remains plausible under the approved linkage rules. Together, these values show the uncertainty arising from record linkage; they are not a statistical confidence interval."), font("`font_body'", 8.2)

putpdf table methods_linkage_note = (1,1), width(100%) border(all, nil)
putpdf table methods_linkage_note(1,1) = ("WHEN READING THE REPORT | A wider linkage uncertainty band means that unresolved record linkage has more influence on the national estimate. It is not a 95% confidence interval."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_linkage_note(1,1), border(top, single, "`bnr_teal'")



** NEW METHODS PAGE. How CVD deaths are classified
putpdf pagebreak
putpdf paragraph
putpdf text ("How CVD deaths are classified"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("BNR mortality surveillance uses death-certificate information to create a consistent practical cardiovascular classification. A formal assigned national underlying cause of death is not currently available to the Registry for routine surveillance. Because death certificates are received in paper form, the BNR first transcribes them into a standard electronic format on behalf of the Government, enabling them to be processed consistently alongside the other registry records."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("How the certificate is interpreted"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A mention of a cardiovascular condition anywhere on a death certificate does not, by itself, mean that CVD is recorded as the underlying cause of death. We consider the wording, its location in Part I or Part II, the order of conditions in Part I, relevant mortality-coding principles and the strength of the supporting evidence. Part I records the sequence leading directly to death, while Part II records other contributing conditions. The position of a condition provides context but is not a simple ranking of diagnoses. On this basis, each death is assigned to one of five evidence classes, described below."), font("`font_body'", 8.4)

putpdf paragraph
putpdf text ("Evidence classes"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table mort_classes = (6,2), width(100%) border(all, nil)
putpdf table mort_classes(1,1) = ("Class")
putpdf table mort_classes(1,2) = ("BNR interpretation")
putpdf table mort_classes(2,1) = ("Clear")
putpdf table mort_classes(2,2) = ("Strong evidence that the death belongs in the relevant BNR cardiovascular mortality group.")
putpdf table mort_classes(3,1) = ("Likely")
putpdf table mort_classes(3,2) = ("Good evidence, although some uncertainty remains.")
putpdf table mort_classes(4,1) = ("Possible")
putpdf table mort_classes(4,2) = ("Cardiovascular attribution is plausible, but uncertainty is material.")
putpdf table mort_classes(5,1) = ("Mention only")
putpdf table mort_classes(5,2) = ("Relevant wording is present but does not support approximate underlying-cause attribution.")
putpdf table mort_classes(6,1) = ("No evidence")
putpdf table mort_classes(6,2) = ("No qualifying cardiovascular evidence is identified by the approved rules.")
putpdf table mort_classes(.,.), font("`font_body'", 7.8)
putpdf table mort_classes(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table mort_classes(.,1), bold

putpdf paragraph
putpdf text ("Heart, Stroke and All CVD"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Heart includes qualifying ischaemic and coronary heart-disease evidence and is not limited to certificates that literally say “heart attack”. Stroke includes qualifying acute ischaemic stroke and non-traumatic cerebral haemorrhage patterns under the approved rules. All CVD combines the resolved Heart and Stroke classifications according to a maintained hierarchy, ensuring that each qualifying death is counted once in the combined CVD estimate."), font("`font_body'", 8.2)

putpdf paragraph
putpdf text ("Primary and Inclusive definitions"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_mort_defs = (3,3), width(100%) border(all, nil)
putpdf table methods_mort_defs(1,1) = ("Definition")
putpdf table methods_mort_defs(1,2) = ("Evidence included")
putpdf table methods_mort_defs(1,3) = ("How to interpret it")
putpdf table methods_mort_defs(2,1) = ("Primary")
putpdf table methods_mort_defs(2,2) = ("Clear + Likely")
putpdf table methods_mort_defs(2,3) = ("The main BNR mortality reporting definition")
putpdf table methods_mort_defs(3,1) = ("Inclusive")
putpdf table methods_mort_defs(3,2) = ("Clear + Likely + Possible")
putpdf table methods_mort_defs(3,3) = ("A broader sensitivity definition that includes more uncertain cardiovascular attribution")
putpdf table methods_mort_defs(.,.), font("`font_body'", 7.7)
putpdf table methods_mort_defs(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_mort_defs(2/3,1), bold

putpdf paragraph
putpdf text ("Relation to official cause-of-death statistics"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The BNR method is a structured approximate-underlying-cause classification for surveillance. It does not implement the full international process for selecting and coding an official ICD-10 underlying cause of death. BNR results should therefore not be assumed to be directly equivalent to official national or international mortality series, even when their labels appear similar."), font("`font_body'", 8.2)

putpdf table methods_mort_note = (1,1), width(100%) border(all, nil)
putpdf table methods_mort_note(1,1) = ///
    ("WHEN READING THE REPORT | Primary is the main series; Inclusive contains Primary plus Possible cardiovascular deaths. They are alternative views of the same burden and must not be added together. Their difference shows classification sensitivity."), ///
    font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_mort_note(1,1), ///
    border(top, single, "`bnr_teal'")



** NEW METHODS PAGE. How the report measures CVD
putpdf paragraph
putpdf text ("How the report measures CVD"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Counts"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("A count is the number of eligible events or classified deaths."), font("`font_body'", 8.4)

* Equation figures are static template assets, rendered from LaTeX so that
* fractions, symbols and subscripts are typeset rather than approximated with
* table cells. They do not contain report data and should not be edited during
* routine annual production.
local methods_equation_dir "$BNR_REPO/scripts/stata/reporting/assets"
local methods_count_eq "`methods_equation_dir'/annual_report_equation_count.png"
local methods_percent_eq "`methods_equation_dir'/annual_report_equation_percentage.png"
local methods_rate_eq "`methods_equation_dir'/annual_report_equation_rate.png"
local methods_asr_eq "`methods_equation_dir'/annual_report_equation_asr.png"

putpdf table methods_count_eq = (1,1), width(14%) border(all, nil) halign(center)
putpdf table methods_count_eq(1,1) = image("`methods_count_eq'"), halign(center)
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Here C is the count and I_i equals one when record i is an eligible event or death and zero otherwise."), font("`font_body'", 7.8, "`bnr_muted'")

putpdf paragraph
putpdf text ("Percentages"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph 
putpdf text ("A percentage describes how a defined eligible total is divided across groups. The denominator must always be checked: a percentage among registered events or classified deaths is not a person's probability of experiencing or dying from CVD."), font("`font_body'", 8.4)

putpdf table methods_percent_eq = (1,1), width(20%) border(all, nil) halign(center)
putpdf table methods_percent_eq(1,1) = image("`methods_percent_eq'"), halign(center)
putpdf paragraph, font("`font_body'", 1)
putpdf text ("Here p is the percentage, n_g is the selected group and N is the relevant eligible total."), font("`font_body'", 7.8, "`bnr_muted'")

putpdf paragraph
putpdf text ("Crude population rate"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table eq_crude = (1,1), width(20%) border(all, nil) halign(center)
putpdf table eq_crude(1,1) = image("`methods_rate_eq'"), halign(center)
putpdf paragraph
putpdf text ("Here R is the rate, E is the eligible event or death count and P is the matching resident population. A crude rate relates the observed number to the matching population and period. It is presented per 100,000 people. The crude rate is useful for describing actual population experience, but comparisons (across different years, between different places) can be complicated by differences in age structure. To solve this comparison problem, we use age-standardised rates. For the Barbados population estimates, we use the United Nations World Population Prospects (2024 edition). Every numerator is paired with the denominator for the same year and, where relevant, the same sex and age group."), font("`font_body'", 8.2)

putpdf paragraph
putpdf text ("Directly age standardised rates"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table eq_asr = (1,1), width(20%) border(all, nil) halign(center)
putpdf table eq_asr(1,1) = image("`methods_asr_eq'"), halign(center)
putpdf paragraph
putpdf text ("ASR is the age-standardised rate, r_a is the rate in age group a and w_a is that group's standard-population weight. This report uses the WHO World Standard Population 2000-2025. Standardisation improves comparisons by applying the same age distribution to every group or year. The ASR is also presented per 100,000 people."), font("`font_body'", 8.2)


** NEW METHODS SECTION (no new page). How the report measured CVD p2 of 2
putpdf paragraph
putpdf text ("Denominators and reported forms"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table methods_rate_map = (5,4), width(100%) border(all, nil)
putpdf table methods_rate_map(1,1) = ("Measure")
putpdf table methods_rate_map(1,2) = ("Numerator")
putpdf table methods_rate_map(1,3) = ("Denominator")
putpdf table methods_rate_map(1,4) = ("Main reported forms")
putpdf table methods_rate_map(2,1) = ("Event rate")
putpdf table methods_rate_map(2,2) = ("Eligible hospital or DCO-enhanced events")
putpdf table methods_rate_map(2,3) = ("Matching Barbados resident population")
putpdf table methods_rate_map(2,4) = ("Crude and age-standardised")
putpdf table methods_rate_map(3,1) = ("Mortality rate")
putpdf table methods_rate_map(3,2) = ("Deaths under the selected BNR definition")
putpdf table methods_rate_map(3,3) = ("Matching Barbados resident population")
putpdf table methods_rate_map(3,4) = ("Crude and age-standardised")
putpdf table methods_rate_map(4,1) = ("Women and men")
putpdf table methods_rate_map(4,2) = ("Sex-specific events or deaths")
putpdf table methods_rate_map(4,3) = ("Resident population of the same sex")
putpdf table methods_rate_map(4,4) = ("Separate published rates")
putpdf table methods_rate_map(5,1) = ("Age pattern")
putpdf table methods_rate_map(5,2) = ("Events or deaths in a broad age groups (<70 years, 70 and older)")
putpdf table methods_rate_map(5,3) = ("Relevant eligible total or age-specific population, as labelled")
putpdf table methods_rate_map(5,4) = ("Count, percentage or crude age-specific rate")
putpdf table methods_rate_map(.,.), font("`font_body'", 7.3)
putpdf table methods_rate_map(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_rate_map(2/5,1), bold

putpdf table methods_measure_note = (1,1), width(100%) border(all, nil)
putpdf table methods_measure_note(1,1) = ("WHEN READING THE REPORT | Counts describe volume. Rates support population comparison. Age-standardised rates support fairer comparison across differently aged populations, and are presented per 100,000 people."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_measure_note(1,1), border(top, single, "`bnr_teal'")




** NEW METHODS PAGE. Understanding uncertainty, comparisons and time
putpdf pagebreak 
putpdf paragraph
putpdf text ("Understanding uncertainty, comparisons and time"), bold font("`font_title'", 14, "`bnr_ink'")
putpdf paragraph
putpdf text ("In this report, we identify different three different types of uncertainty. The statistical variation around our estimated event and mortality rates, the uncertainty associated with unresolved record linkage, and the uncertainty associated with our mortality classification (which identifies the 5 evidence classes described)."), font("`font_body'", 8.4)

putpdf table methods_uncertainty = (5,3), width(100%) border(all, nil)
putpdf table methods_uncertainty(1,1) = ("What is shown")
putpdf table methods_uncertainty(1,2) = ("How it appears")
putpdf table methods_uncertainty(1,3) = ("What it means")
putpdf table methods_uncertainty(2,1) = ("Statistical 95% confidence interval")
putpdf table methods_uncertainty(2,2) = ("Vertical whiskers")
putpdf table methods_uncertainty(2,3) = ("Statistical variation around the published rate")
putpdf table methods_uncertainty(3,1) = ("DCO linkage range")
putpdf table methods_uncertainty(3,2) = ("Pale transparent band")
putpdf table methods_uncertainty(3,3) = ("How unresolved linkage might affect an annual national event estimate")
putpdf table methods_uncertainty(4,1) = ("Primary and Inclusive mortality")
putpdf table methods_uncertainty(4,2) = ("Separate lines or values")
putpdf table methods_uncertainty(4,3) = ("Sensitivity to including Possible cardiovascular deaths")
putpdf table methods_uncertainty(5,1) = ("Previous-five-year mean")
putpdf table methods_uncertainty(5,2) = ("Comparator line or value")
putpdf table methods_uncertainty(5,3) = ("Historical context, not an uncertainty interval or forecast")
putpdf table methods_uncertainty(.,.), font("`font_body'", 7.3)
putpdf table methods_uncertainty(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table methods_uncertainty(2/5,1), bold

putpdf paragraph
putpdf text ("Statistical confidence intervals"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Published crude-rate intervals use the exact Poisson (Garwood) method where specified. Published directly age-standardised rates use the Fay-Feuer gamma method."), font("`font_body'", 8.2)

putpdf table methods_uncertainty_note = (1,1), width(100%) border(all, nil)
putpdf table methods_uncertainty_note(1,1) = ("WHEN READING THE REPORT | Do not combine a statistical confidence interval, a DCO linkage range and the Primary-Inclusive difference into one overall interval. They answer different questions."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_uncertainty_note(1,1), border(top, single, "`bnr_teal'")




** NEW METHODS PAGE. Data quality, confidentiality and publication
putpdf pagebreak
putpdf paragraph
putpdf text ("Data quality, confidentiality and publication"), ///
    bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Data quality metrics in Chapter 3"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("National event estimates combine eligible hospital events with qualifying events identified from death certificates, so they are not limited to people who reach hospital. The Chapter 3 measures show how much national event estimates rely on these death-record events and how much mortality totals rely on the less-certain "), font("`font_body'", 8.2)

putpdf text ("Possible "), italic  font("`font_body'", 8.2) 
putpdf text ("class. They are quality and sensitivity summaries, not measures of individual risk and not judgements that a particular record is correct or incorrect."),  font("`font_body'", 8.2) 


putpdf table methods_quality_eq = (2,2), width(100%) border(all, nil)

putpdf table methods_quality_eq(1,1) = ("DCO contribution")
putpdf table methods_quality_eq(1,2) = ///
    ("Shows how much national event estimates increase when eligible death-certificate-only events are included alongside hospital events.")

putpdf table methods_quality_eq(2,1) = ("Possible-death reliance")
putpdf table methods_quality_eq(2,2) = ///
    ("Shows how much the Inclusive mortality estimate depends on deaths where cardiovascular disease is possible, but less certain.")

putpdf table methods_quality_eq(.,.), font("`font_body'", 7.7)
putpdf table methods_quality_eq(.,1), ///
    bold font("`font_title'", 7.7, "`bnr_teal'")
putpdf table methods_quality_eq(1,.), ///
    border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Three kinds of uncertainty"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf table methods_uncertainty = (3,2), width(100%) border(all, nil)

putpdf table methods_uncertainty(1,1) = ("Statistical uncertainty")
putpdf table methods_uncertainty(1,2) = ///
    ("The natural variation in rates calculated from relatively small numbers.")

putpdf table methods_uncertainty(2,1) = ("Classification sensitivity")
putpdf table methods_uncertainty(2,2) = ///
    ("How mortality results change when Possible cardiovascular deaths are included.")

putpdf table methods_uncertainty(3,1) = ("Linkage uncertainty")
putpdf table methods_uncertainty(3,2) = ///
    ("The plausible effect where death and hospital records cannot be linked with complete certainty.")

putpdf table methods_uncertainty(.,.), font("`font_body'", 7.7)
putpdf table methods_uncertainty(.,1), ///
    bold font("`font_title'", 7.7, "`bnr_teal'")
putpdf table methods_uncertainty(1,.), ///
    border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Completeness"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("Where completeness is reported, it shows the proportion of eligible records containing the required information. Information that is genuinely not applicable is not counted as missing. Changes in completeness can alter apparent patterns without a corresponding change in disease burden."), ///
    font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Confidentiality"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("BNR publishes totals and rates, not patient-level records. Small counts may be withheld, and further checks prevent protected values being worked out from totals or comparisons across releases. A person reviews each proposed public release before approval. Suppressed means not published, not zero."), ///
    font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Before publication"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("The underlying data are prepared, checked, reviewed and approved before publication. The annual report uses these approved public data releases and does not change the underlying results."), ///
    font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Responsible interpretation"), ///
    bold font("`font_title'", 11, "`bnr_ink'")

putpdf paragraph
putpdf text ("Changes may reflect health, health-care access, diagnosis, recording, completeness, population estimates or several factors together. Compare like with like; distinguish events from people and hospital-recorded results from national estimates; consider each form of uncertainty separately; and interpret small annual changes cautiously. Surveillance patterns can guide decisions and questions, but do not by themselves prove why a change occurred."), ///
    font("`font_body'", 8.1)

putpdf table methods_final_note = (1,1), width(100%) border(all, nil)

putpdf table methods_final_note(1,1) = ///
    ("WHEN READING THE REPORT | Definitions, source coverage, period, denominator, completeness and uncertainty are part of every result, not optional footnotes to the number."), ///
    font("`font_title'", 8.2, "`bnr_teal'")

putpdf table methods_final_note(1,1), ///
    border(top, single, "`bnr_teal'")


/*

** NEW METHODS PAGE. Data quality, confidentiality and publication
putpdf pagebreak
putpdf paragraph
putpdf text ("Data quality, confidentiality and publication"), bold font("`font_title'", 14, "`bnr_ink'")

putpdf paragraph
putpdf text ("Data quality indicators"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("In Chapter 3, we describe how strongly national event estimates rely on death-record ascertainment and how strongly mortality totals rely on the less-certain "), font("`font_body'", 8.2)
putpdf text ("Possible "), italic font("`font_body'", 8.2) append
putpdf text ("class. They are quality and sensitivity summaries, not measures of individual risk and not judgements that a particular record is correct or incorrect."), font("`font_body'", 8.2) append

putpdf table methods_quality_eq = (2,2), width(100%) border(all, nil)
putpdf table methods_quality_eq(1,1) = ("DCO contribution")
putpdf table methods_quality_eq(1,2) = ("estimated additional DCO events / Primary national event estimate × 100")
putpdf table methods_quality_eq(2,1) = ("Possible-death reliance")
putpdf table methods_quality_eq(2,2) = ("Possible-only deaths / Inclusive mortality count × 100")
putpdf table methods_quality_eq(.,.), font("`font_body'", 7.7)
putpdf table methods_quality_eq(.,1), bold font("`font_title'", 7.7, "`bnr_teal'")
putpdf table methods_quality_eq(1,.), border(top, single, "`bnr_teal'")

putpdf paragraph
putpdf text ("Disclosure control"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("The BNR publishes only aggregate summaries of CVD burden. As part of our publication process, exact counts from 1 to 5 require primary suppression and are never released. Secondary suppression protects values recoverable from totals, while derived and temporal protections address calculated outputs and differencing across releases. After disclosure control has been completed, every potential data or report release is reviewed by a BNR analyst before approval. Suppressed means not published, not zero, and the protected value can never be reconstructed from any combination of secondary values."), font("`font_body'", 8.1)

putpdf paragraph
putpdf text ("Two controlled production pathways"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf table workflow = (3,3), width(100%) border(all, nil)
putpdf table workflow(1,1) = ("Pathway")
putpdf table workflow(1,2) = ("Controlled stages")
putpdf table workflow(1,3) = ("Boundary")
putpdf table workflow(2,1) = ("Data releases / Dashboards / Tabulations")
putpdf table workflow(2,2) = ("Prepare → calculate → review → approve → publish")
putpdf table workflow(2,3) = ("Creates approved aggregate CVD-event and mortality products from controlled analytical inputs")
putpdf table workflow(3,1) = ("Annual report")
putpdf table workflow(3,2) = ("Build report → approve report → publish")
putpdf table workflow(3,3) = ("Reads declared public releases; it does not repeat classification, linkage, calculation or suppression")
putpdf table workflow(.,.), font("`font_body'", 7.5)
putpdf table workflow(1,.), bold bgcolor("`bnr_white'") ///
    border(top, single, "`bnr_teal'") border(bottom, single, "`bnr_rule'")
putpdf table workflow(2/3,1), bold font("`font_title'", 7.5, "`bnr_teal'")

putpdf paragraph
putpdf text ("Responsible interpretation"), bold font("`font_title'", 11, "`bnr_ink'")
putpdf paragraph
putpdf text ("Changes may reflect health, health-care access, diagnosis, recording, completeness, population estimates or several factors together. Compare like with like; distinguish events from people and hospital-recorded results from national estimates; consider all three forms of uncertainty separately; and interpret small annual changes cautiously. Surveillance patterns can guide decisions and questions, but do not by themselves prove why a change occurred."), font("`font_body'", 8.1)

putpdf table methods_final_note = (1,1), width(100%) border(all, nil)
putpdf table methods_final_note(1,1) = ("WHEN READING THE REPORT | Definitions, source coverage, period, denominator, completeness and uncertainty are part of every result, not optional footnotes to the number."), font("`font_title'", 8.2, "`bnr_teal'")
putpdf table methods_final_note(1,1), border(top, single, "`bnr_teal'")
