{smcl}
{title:BNR Mortality Step 5: Record human approval}

{p 4 4 2}
{cmd:db bnr_mort_s5_approve} opens the mortality Step 5 approval dialog.
Use it only after Step 4 has completed and an authorised analyst has reviewed
the Step 4 workbook and exact disclosure-controlled public candidate.

{title:Purpose}

{p 4 4 2}
Mortality Step 5 is deliberately an approval gate. It does not calculate
mortality measures and it does not apply, change or improve suppression. Those
tasks are complete before approval. Step 5 instead confirms that the exact
files reviewed in Step 4 are unchanged, records the authorised human decision,
and creates the private staging {cmd:public_ready/} package for Step 6.

{title:Before approval}

{p 4 4 2}
Open {cmd:review/mort_s4_review_mort_YYYY_MM.xlsx}. Use the workbook in this
practical order: (1) {bf:Review summary} and {bf:QA}; (2) {bf:Definitions} and
the annual, quarterly and monthly private metrics sheets; (3) the private
{bf:Suppression review}; (4) {bf:Monthly reference}; and (5) {bf:Public candidate}.

{p 4 4 2}
The Suppression review sheet contains the exact private values, supporting
fields and a plain-language protection route. Inspect every primary row and
each secondary-protection route there. Then use the displayed metric keys to
find the same rows in Public candidate. Confirm that {cmd:value},
{cmd:numerator}, {cmd:denominator} and {cmd:comparison_n} are blank,
{cmd:display_value} is {cmd:*}, and {cmd:suppression_status} is {cmd:primary}
or {cmd:secondary}. This is a spreadsheet review; no code or manual rewriting
of the generated outputs is required.

{p 4 4 2}
If review identifies a problem, do not edit the workbook, candidate or any
other generated file. Correct the appropriate source or version-controlled
code, rerun the earlier workflow step, rerun Step 4, and repeat the human
review.

{title:Approval confirmations}

{p 4 4 2}
One authorised BNR Lead, BNR Analyst or BNR Developer must supply their full
name and tick all five confirmations. Complete the concrete review action in
each item before ticking it:

{p 8 12 2}
1. In Review summary and QA, confirm the selected release and reporting period
and that every Step 3 and Step 4 QA check is PASS;

{p 8 12 2}
2. In Definitions and the private annual, quarterly and monthly metrics sheets,
review the two case definitions and spot-check counts, percentages and the
quarterly/annual comparator values for analytical plausibility. Monthly rows
have no rolling comparator;

{p 8 12 2}
3. In the private Suppression review sheet, inspect every primary row, each
plain-language secondary-protection route and the reported suppression totals;

{p 8 12 2}
4. In Monthly reference, check that both mortality definitions have twelve
same-calendar-month rows, based on 2015-2019, with five contributing years and
minimum, maximum and mean values. In Public candidate, confirm monthly rows
are all-CVD, both sexes and all ages only; use the same metric keys to confirm
protected rows are displayed as asterisks with blank exact fields, and
spot-check unrestricted rows against the private metrics sheets; and

{p 8 12 2}
5. Confirm that the reviewed candidate, QA receipt and workbook together are
the intended, unchanged package for Step 6 publication processing.

{title:Command-line syntax}

{p 8 8 2}
{cmd:do "$BNR_STATA/mortality/bnr_mort_s5_approve.do"} {it:year} {it:month}
{it:"Full name"} {it:"BNR Lead"|"BNR Analyst"|"BNR Developer"}
{cmd:release definitions disclosure candidate ready}

{p 8 8 2}
Example:
{cmd:. do "$BNR_STATA/mortality/bnr_mort_s5_approve.do" 2026 7 "Full name" "BNR Analyst" release definitions disclosure candidate ready}

{title:Checks performed}

{p 4 4 2}
Step 5 requires all Step 4 review artefacts, requires all 16 Step 4 QA checks
to pass, revalidates the candidate schema, the fixed monthly-reference asset
and the disclosure-control contract, rejects common person-level identifiers,
and recomputes all 14 file fingerprints in the Step 4 review-basis receipt. Any changed, missing or
unexpected file stops approval. It does not repeat Step 4's disclosure-control
calculation or ask the analyst to alter a generated file.

{title:Successful outputs}

{p 4 4 2}
Only after every check passes, Step 5 creates
{cmd:$BNR_STAGING/mortality/burden/mort_YYYY_MM/public_ready/} containing:

{p 8 12 2}
- release-stamped and current DTA/CSV datasets;

{p 8 12 2}
- release, current and package YAML metadata;

{p 8 12 2}
- the fixed 2015-2019 monthly-reference DTA/CSV and its metadata;

{p 4 4 2}
The public-ready reference metadata is generated by Step 5 with an
{cmd:approved_reference_asset} status and points to {cmd:approval.yml}; it does
not retain Step 4's review-candidate wording.

{p 8 12 2}
- {cmd:public_manifest.csv}, fingerprinting the ten payload files; and

{p 8 12 2}
- {cmd:approval.yml}, written last and binding the approval to the manifest.

{p 4 4 2}
The release-stamped and current files are intentionally identical at approval.
The stable current names support later dashboard and download consumers. Step 6
must validate the manifest and approval before promotion.

{title:Suppression contract}

{p 4 4 2}
Protected rows remain in the candidate and public-ready datasets, but their
exact numeric results and supporting counts are missing. {cmd:display_value}
contains {cmd:*}; {cmd:suppression_status} is {cmd:primary} or {cmd:secondary};
and {cmd:disclosure_note} explains the decision. Unrestricted rows use
{cmd:none}. Consumers must read {cmd:suppression_status}; a missing value alone
does not establish suppression. Step 4's passed {cmd:disclosure_control} QA
check confirms that its fixed primary and secondary-protection rules have been
applied. Step 5 binds the approval to that reviewed candidate; it does not ask
an analyst to choose, edit or recalculate suppression. Quarterly and annual
comparator rows marked {cmd:insufficient_history} legitimately have no value
and are not suppressed. Monthly rolling comparator rows are deliberately
absent; the approved fixed reference is used instead.

{title:Synthetic test protection}

{p 4 4 2}
The reserved 2099 suppression-test release can be used to test Steps 3 and 4,
but Step 5 deliberately refuses to approve it. Synthetic test files must remain
under the repository test area and must never enter a public-ready package.

{title:Publication boundary}

{p 4 4 2}
Step 5 creates no authoritative public output, download, website file, Quarto
output or GitHub change. {cmd:public_ready} means approved for Step 6 processing;
it does not mean published. Step 6 alone may promote a valid approved package.

{title:End-of-run status}

{p 4 4 2}
Routine Stata commands run quietly. A successful run ends with a clearly
separated {bf:MORTALITY STEP 5: OPERATIONAL RUN SUMMARY} showing
{bf:APPROVED - PENDING STEP 6}, the approver, row and suppression counts,
public-ready folder, manifest, approval receipt and private log.

{p 4 4 2}
A controlled failure ends with the same summary heading, reports
{bf:Did not complete}, states the reason and confirms that no public or website
output was created.
